import type { AttributionClaim } from "../address-attribution";

/**
 * Hand-curated set of well-known crypto addresses.
 *
 * These are the highest-signal nodes in the graph: every CEX hot wallet,
 * foundation multisig, mixer, lost-coins relic, and major-hack proceeds
 * destination that an investigator should see at-a-glance.
 *
 * Curation rules:
 *  - One entry per well-known address; sources independently verifiable
 *    (Etherscan public labels, contract deployer pages, foundation
 *    governance posts, well-publicised incident reports).
 *  - `confidence: 90` for community-attested, `95` for protocol-confirmed,
 *    `100` for foundation/incident-confirmed via primary source.
 *  - All EVM addresses lowercased; bitcoin/solana preserved verbatim.
 *  - No Casper / CSPR entries (excluded per founder policy).
 */

type CuratedEntry = Omit<AttributionClaim, "source" | "reportedAt"> & {
  sourceRef: string;
};

export const CURATED_ADDRESSES: CuratedEntry[] = [
  // ============================================================
  // EXCHANGES — CEX hot/cold wallets (Ethereum)
  // ============================================================
  {
    chain: "ethereum",
    address: "0x28c6c06298d514db089934071355e5743bf21d60",
    sourceRef: "binance-14",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 14",
    notes: "One of Binance's largest ETH hot wallets",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x21a31ee1afc51d94c2efccaa2092ad1028285549",
    sourceRef: "binance-15",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 15",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xdfd5293d8e347dfe59e90efd55b2956a1343963d",
    sourceRef: "binance-16",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 16",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x564286362092d8e7936f0549571a803b203aaced",
    sourceRef: "binance-17",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 17",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x0681d8db095565fe8a346fa0277bffde9c0edbbf",
    sourceRef: "binance-18",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 18",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xfe9e8709d3215310075d67e3ed32a380ccf451c8",
    sourceRef: "binance-19",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 19",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x4e5b2e1dc63f6b91cb6cd759936495434c7e972f",
    sourceRef: "binance-20",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 20",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xf977814e90da44bfa03b6295a0616a897441acec",
    sourceRef: "binance-peg-tokens",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance: Binance-Peg Tokens",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x5a52e96bacdabb82fd05763e25335261b270efcb",
    sourceRef: "binance-deposit",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance Deposit",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x71660c4005ba85c37ccec55d0c4493e66fe775d3",
    sourceRef: "coinbase-1",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 1",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x503828976d22510aad0201ac7ec88293211d23da",
    sourceRef: "coinbase-2",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xddfabcdc4d8ffc6d5beaf154f18b778f892a0740",
    sourceRef: "coinbase-3",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 3",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x3cd751e6b0078be393132286c442345e5dc49699",
    sourceRef: "coinbase-4",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 4",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511",
    sourceRef: "coinbase-5",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 5",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xeb2629a2734e272bcc07bda959863f316f4bd4cf",
    sourceRef: "coinbase-6",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 6",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa9d1e08c7793af67e9d92fe308d5697fb81d3e43",
    sourceRef: "coinbase-8",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 8",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x77696bb39917c91a0c3908d577d5e322095425ca",
    sourceRef: "coinbase-9",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 9",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x7c195d981abfdc3ddecd2ca0fed0958430488e34",
    sourceRef: "coinbase-10",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 10",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x2910543af39aba0cd09dbb2d50200b3e800a63d2",
    sourceRef: "kraken-1",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 1",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x0a869d79a7052c7f1b55a8ebabbea3420f0d1e13",
    sourceRef: "kraken-2",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xe853c56864a2ebe4576a807d26fdc4a0ada51919",
    sourceRef: "kraken-3",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 3",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0",
    sourceRef: "kraken-4",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 4",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa910f92acdaf488fa6ef02174fb86208ad7722ba",
    sourceRef: "okx-1",
    category: "exchange",
    ownerName: "OKX",
    ownerKind: "exchange",
    label: "OKX Hot Wallet 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x236f9f97e0e62388479bf9e5ba4889e46b0273c3",
    sourceRef: "okx-2",
    category: "exchange",
    ownerName: "OKX",
    ownerKind: "exchange",
    label: "OKX Hot Wallet 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xf89d7b9c864f589bbf53a82105107622b35eaa40",
    sourceRef: "bybit-hot",
    category: "exchange",
    ownerName: "Bybit",
    ownerKind: "exchange",
    label: "Bybit Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x1ab4973a48dc892cd9971ece8e01dcc7688f8f23",
    sourceRef: "kucoin-1",
    category: "exchange",
    ownerName: "KuCoin",
    ownerKind: "exchange",
    label: "KuCoin 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xd6216fc19db775df9774a6e33526131da7d19a2c",
    sourceRef: "kucoin-2",
    category: "exchange",
    ownerName: "KuCoin",
    ownerKind: "exchange",
    label: "KuCoin 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x77134cbc06cb00b66f4c7e623d5fdbf6777635ec",
    sourceRef: "bitfinex-1",
    category: "exchange",
    ownerName: "Bitfinex",
    ownerKind: "exchange",
    label: "Bitfinex Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0d0707963952f2fba59dd06f2b425ace40b492fe",
    sourceRef: "gateio-1",
    category: "exchange",
    ownerName: "Gate.io",
    ownerKind: "exchange",
    label: "Gate.io Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x6262998ced04146fa42253a5c0af90ca02dfd2a3",
    sourceRef: "cryptocom-1",
    category: "exchange",
    ownerName: "Crypto.com",
    ownerKind: "exchange",
    label: "Crypto.com 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x46340b20830761efd32832a74d7169b29feb9758",
    sourceRef: "cryptocom-2",
    category: "exchange",
    ownerName: "Crypto.com",
    ownerKind: "exchange",
    label: "Crypto.com 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xd24400ae8bfebb18ca49be86258a3c749cf46853",
    sourceRef: "gemini-1",
    category: "exchange",
    ownerName: "Gemini",
    ownerKind: "exchange",
    label: "Gemini Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
    sourceRef: "bittrex-1",
    category: "exchange",
    ownerName: "Bittrex",
    ownerKind: "exchange",
    label: "Bittrex Hot Wallet",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x59a5208b32e627891c389ebafc644145224006e8",
    sourceRef: "huobi-1",
    category: "exchange",
    ownerName: "HTX (Huobi)",
    ownerKind: "exchange",
    label: "Huobi 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xab5c66752a9e8167967685f1450532fb96d5d24f",
    sourceRef: "huobi-2",
    category: "exchange",
    ownerName: "HTX (Huobi)",
    ownerKind: "exchange",
    label: "Huobi 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xe93381fb4c4f14bda253907b18fad305d799241a",
    sourceRef: "huobi-3",
    category: "exchange",
    ownerName: "HTX (Huobi)",
    ownerKind: "exchange",
    label: "Huobi 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x75e89d5979e4f6fba9f97c104c2f0afb3f1dcb88",
    sourceRef: "mexc-1",
    category: "exchange",
    ownerName: "MEXC",
    ownerKind: "exchange",
    label: "MEXC Hot Wallet",
    confidence: 95,
  },

  // ============================================================
  // EXCHANGES — Bitcoin cold wallets
  // ============================================================
  {
    chain: "bitcoin",
    address: "bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97",
    sourceRef: "binance-btc-cold",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance BTC Cold Wallet",
    notes: "~250k BTC cluster; well-known Binance reserves",
    confidence: 95,
  },
  {
    chain: "bitcoin",
    address: "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo",
    sourceRef: "binance-btc-cold-2",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance BTC Cold Storage",
    confidence: 95,
  },
  {
    chain: "bitcoin",
    address: "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2",
    sourceRef: "coinbase-btc-cold",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase BTC Cold Wallet",
    confidence: 95,
  },

  // ============================================================
  // FOUNDATIONS — protocol treasuries / multisigs
  // ============================================================
  {
    chain: "ethereum",
    address: "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
    sourceRef: "ethereum-foundation-1",
    category: "foundation",
    ownerName: "Ethereum Foundation",
    ownerKind: "foundation",
    label: "Ethereum Foundation",
    notes: "Primary EF treasury address",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359",
    sourceRef: "ethereum-foundation-2",
    category: "foundation",
    ownerName: "Ethereum Foundation",
    ownerKind: "foundation",
    label: "Ethereum Foundation 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x9bf4001d307dfd62b26a2f1307ee0c0307632d59",
    sourceRef: "ethereum-foundation-multisig",
    category: "foundation",
    ownerName: "Ethereum Foundation",
    ownerKind: "foundation",
    label: "EF Multisig",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x25e2e8d104bc1a70492e2be32da7c1f8367f9d39",
    sourceRef: "uniswap-treasury",
    category: "treasury",
    ownerName: "Uniswap",
    ownerKind: "dao",
    label: "Uniswap DAO Treasury",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x1a9c8182c09f50c8318d769245bea52c32be35bc",
    sourceRef: "uniswap-timelock",
    category: "treasury",
    ownerName: "Uniswap",
    ownerKind: "dao",
    label: "Uniswap Timelock",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    sourceRef: "weth-contract",
    category: "defi-protocol",
    ownerName: "WETH",
    ownerKind: "protocol",
    label: "Wrapped Ether (WETH)",
    notes: "Canonical WETH contract",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    sourceRef: "usdc-contract",
    category: "defi-protocol",
    ownerName: "Circle",
    ownerKind: "protocol",
    label: "USDC Token Contract",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    sourceRef: "usdt-contract",
    category: "defi-protocol",
    ownerName: "Tether",
    ownerKind: "protocol",
    label: "Tether USD (USDT)",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6b175474e89094c44da98b954eedeac495271d0f",
    sourceRef: "dai-contract",
    category: "defi-protocol",
    ownerName: "MakerDAO",
    ownerKind: "dao",
    label: "DAI Stablecoin",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x4da27a545c0c5b758a6ba100e3a049001de870f5",
    sourceRef: "aave-stkaave",
    category: "defi-protocol",
    ownerName: "Aave",
    ownerKind: "dao",
    label: "Aave Safety Module (stkAAVE)",
    confidence: 100,
  },

  // ============================================================
  // PERSONALITIES — well-known publicly-known individuals
  // ============================================================
  {
    chain: "ethereum",
    address: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
    sourceRef: "vitalik-eth",
    category: "personality",
    ownerName: "Vitalik Buterin",
    ownerKind: "individual",
    label: "vitalik.eth",
    notes: "Primary public address (vitalik.eth)",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xab5801a7d398351b8be11c439e05c5b3259aec9b",
    sourceRef: "vitalik-second",
    category: "personality",
    ownerName: "Vitalik Buterin",
    ownerKind: "individual",
    label: "Vitalik Buterin (secondary)",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x220866b1a2219f40e72f5c628b65d54268ca3a9d",
    sourceRef: "vitalik-old",
    category: "personality",
    ownerName: "Vitalik Buterin",
    ownerKind: "individual",
    label: "Vitalik Buterin (historical)",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x91c987bf62d25945db517bdaa840a6c661374402",
    sourceRef: "kevin-rose",
    category: "personality",
    ownerName: "Kevin Rose",
    ownerKind: "individual",
    label: "Kevin Rose (hacked Jan 2023)",
    notes: "Lost ~$1.1M in NFT phishing attack 2023-01",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x3ddfa8ec3052539b6c9549f12cea2c295cff5296",
    sourceRef: "justin-sun-1",
    category: "personality",
    ownerName: "Justin Sun",
    ownerKind: "individual",
    label: "Justin Sun (Tron founder)",
    confidence: 85,
  },

  // ============================================================
  // MARKET MAKERS
  // ============================================================
  {
    chain: "ethereum",
    address: "0x0000000000a39bb272e79075ade125fd351887ac",
    sourceRef: "wintermute-1",
    category: "market-maker",
    ownerName: "Wintermute",
    ownerKind: "market-maker",
    label: "Wintermute Trading",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x4f3a120e72c76c22ae802d129f599bfdbc31cb81",
    sourceRef: "wintermute-2",
    category: "market-maker",
    ownerName: "Wintermute",
    ownerKind: "market-maker",
    label: "Wintermute 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x56178a0d5f301baf6cf3e1cd53d9863437345bf9",
    sourceRef: "jump-1",
    category: "market-maker",
    ownerName: "Jump Trading",
    ownerKind: "market-maker",
    label: "Jump Trading",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0xf3b0073e3a7f747c7a38b36b805247b222c302a3",
    sourceRef: "alameda-1",
    category: "market-maker",
    ownerName: "Alameda Research (defunct)",
    ownerKind: "criminal-group",
    label: "Alameda Research",
    notes: "SBF-controlled MM, collapsed Nov 2022, criminal conviction",
    confidence: 100,
  },

  // ============================================================
  // MIXERS (most also OFAC-sanctioned — both attributions stored)
  // ============================================================
  {
    chain: "ethereum",
    address: "0x8589427373d6d84e98730d7795d8f6f8731fda16",
    sourceRef: "tornado-router",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash Router",
    notes: "OFAC-sanctioned 2022-08",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x910cbd523d972eb0a6f4cae4618ad62622b39dbf",
    sourceRef: "tornado-10eth",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash 10 ETH",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x47ce0c6ed5b0ce3d3a51fdb1c52dc66a7c3c2936",
    sourceRef: "tornado-100eth",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash 100 ETH",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc",
    sourceRef: "tornado-1eth",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash 1 ETH",
    confidence: 100,
  },

  // ============================================================
  // FAMOUS LOST / DORMANT / SATOSHI-ERA
  // ============================================================
  {
    chain: "bitcoin",
    address: "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
    sourceRef: "btc-largest-dormant",
    category: "dormant",
    ownerName: "Unknown (largest dormant BTC wallet)",
    ownerKind: "unknown",
    label: "79,957 BTC dormant since 2011",
    notes: "Holds ~80k BTC, untouched since April 2011. Possibly Mt. Gox-related.",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "12ib7dApVFvg82TXKycWBNpN8kFyiAN1dr",
    sourceRef: "btc-mt-gox-1",
    category: "lost",
    ownerName: "Mt. Gox bankruptcy estate",
    ownerKind: "estate",
    label: "Mt. Gox Cold Wallet",
    notes: "~200k BTC recovered, being distributed to creditors 2024+",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "1933phfhK3ZgFQNLGSDXvqCn32k2buXY8a",
    sourceRef: "btc-block-9-recipient",
    category: "dormant",
    ownerName: "Hal Finney (likely)",
    ownerKind: "individual",
    label: "First Bitcoin transaction recipient (Block 170)",
    notes: "Received 10 BTC from Satoshi on 2009-01-12 — first ever BTC transaction",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "1HLoD9E4SDFFPDiYfNYnkBLQ85Y51J3Zb1",
    sourceRef: "btc-satoshi-candidate",
    category: "dormant",
    ownerName: "Satoshi Nakamoto (suspected)",
    ownerKind: "individual",
    label: "Patoshi-pattern early miner",
    notes: "Patoshi-pattern early mining address — never moved coins",
    confidence: 75,
  },

  // ============================================================
  // GOVERNMENT-SEIZED
  // ============================================================
  {
    chain: "bitcoin",
    address: "bc1qa5wkgaew2dkv56kfvj49j0av5nml45x9ek9hz6",
    sourceRef: "doj-bitfinex-hack-seizure",
    category: "government-seized",
    ownerName: "US DOJ (Bitfinex 2016 hack seizure)",
    ownerKind: "government",
    label: "DOJ: Bitfinex Hack Seizure",
    notes: "94,643 BTC seized from Heather Morgan & Ilya Lichtenstein in 2022",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "bc1qf3tcfg9gqgpxh3cy6m0lhrm0gxyvmgcdzdy7m4",
    sourceRef: "doj-silkroad-2020",
    category: "government-seized",
    ownerName: "US DOJ (Silk Road seizure 2020)",
    ownerKind: "government",
    label: "DOJ: Silk Road 'Individual X' Seizure",
    notes: "69,370 BTC seized in Nov 2020",
    confidence: 100,
  },

  // ============================================================
  // HACK SOURCES (well-documented incident wallets)
  // ============================================================
  {
    chain: "ethereum",
    address: "0x098b716b8aaf21512996dc57eb0615e2383e2f96",
    sourceRef: "ronin-bridge-hack",
    category: "hack-destination",
    ownerName: "Lazarus Group / Ronin Bridge Hack",
    ownerKind: "criminal-group",
    label: "Ronin Bridge Hacker (DPRK Lazarus)",
    notes: "$625M Ronin Bridge hack 2022-03-23. OFAC-sanctioned 2022-04.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x630956ea50abd6caafac75ba3b9c52c2cb0b1cd0",
    sourceRef: "wormhole-hack",
    category: "hack-source",
    ownerName: "Wormhole Bridge Exploit",
    ownerKind: "criminal-group",
    label: "Wormhole Hacker",
    notes: "$325M cross-chain bridge exploit 2022-02-02",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x56eddb7aa87536c09ccc2793473599fd21a8b17f",
    sourceRef: "nomad-bridge-hack",
    category: "hack-source",
    ownerName: "Nomad Bridge Exploit",
    ownerKind: "criminal-group",
    label: "Nomad Bridge Drain",
    notes: "$190M chaotic-drain exploit 2022-08-01",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xc8a65fadf0e0ddaf421f28feab69bf6e2e589963",
    sourceRef: "poly-network-hack",
    category: "hack-source",
    ownerName: "Poly Network Exploit (funds returned)",
    ownerKind: "individual",
    label: "Poly Network 'Mr. White Hat'",
    notes: "$611M Poly Network exploit 2021-08; funds returned",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x1c5dcdd006ea78a7e4783f9e6021c32935a10fb4",
    sourceRef: "beanstalk-flashloan-exploiter",
    category: "hack-source",
    ownerName: "Beanstalk Farms Governance Exploit",
    ownerKind: "criminal-group",
    label: "Beanstalk Flashloan Exploiter",
    notes: "$182M Beanstalk Farms flash-loan governance exploit 2022-04-17. Attacker net profit ~$76M (24,930 ETH). Etherscan public label.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x59abf3837fa962d6853b4cc0a19513aa031fd32b",
    sourceRef: "ftx-accounts-drainer",
    category: "hack-source",
    ownerName: "FTX Accounts Drainer",
    ownerKind: "unknown",
    label: "FTX Accounts Drainer",
    notes: "$477M drained from FTX wallets during 2022-11-12 bankruptcy. Etherscan public label; attribution still debated (insider vs. external). Previously misattributed in this seed as Beanstalk Exploiter.",
    confidence: 100,
  },
  // ftx-exploit-2022 entry removed: address 0x4b8d3a4c1c4d3e2e76aeec0b6cc6b6cd1d5e8d8d
  // does not appear in any FTX-hack coverage and its repeating hex pattern
  // suggests it was fabricated. Real FTX Accounts Drainer attribution is at
  // 0x59abf3837...d32b (Etherscan public label) — written above as
  // `ftx-accounts-drainer`. Stale prod row is dropped by
  // scripts/cleanup-stale-attributions.ts.
  {
    chain: "ethereum",
    address: "0x0fa09c3a328792253f8dee7116848723b72a6d2e",
    sourceRef: "euler-finance-hack",
    category: "hack-destination",
    ownerName: "Euler Finance Exploit (funds returned)",
    ownerKind: "individual",
    label: "Euler Finance Exploiter",
    notes: "$197M flash loan exploit 2023-03-13; majority returned",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6cf9aa65ebad7028536e353393630e2340ca6049",
    sourceRef: "bybit-2025-hack",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit $1.4B Hack",
    notes: "$1.4B Bybit hack 2025-02-21, attributed to Lazarus by FBI",
    confidence: 100,
  },

  // ============================================================
  // VALIDATORS / STAKING
  // ============================================================
  {
    chain: "ethereum",
    address: "0x00000000219ab540356cbb839cbe05303d7705fa",
    sourceRef: "eth2-deposit-contract",
    category: "validator",
    ownerName: "Ethereum",
    ownerKind: "foundation",
    label: "ETH2 Beacon Deposit Contract",
    notes: "Canonical ETH staking deposit contract",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xae7ab96520de3a18e5e111b5eaab095312d7fe84",
    sourceRef: "lido-steth",
    category: "validator",
    ownerName: "Lido",
    ownerKind: "dao",
    label: "Lido stETH Token",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xbe9895146f7af43049ca1c1ae358b0541ea49704",
    sourceRef: "coinbase-cbeth",
    category: "validator",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase Wrapped Staked ETH (cbETH)",
    confidence: 100,
  },

  // ============================================================
  // BRIDGES — L1 escrows for major L2s + cross-chain bridges. Hand-curated
  // since L2Beat's public projects endpoint went dark (see
  // src/lib/harvesters/l2beat.ts STATUS comment).
  // ============================================================
  {
    chain: "ethereum",
    address: "0x3154cf16ccdb4c6d922629664174b904d80f2c35",
    sourceRef: "base-bridge",
    category: "bridge",
    ownerName: "Base",
    ownerKind: "protocol",
    label: "Base L1 Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x49048044d57e1c92a77f79988d21fa8faf74e97e",
    sourceRef: "base-portal",
    category: "bridge",
    ownerName: "Base",
    ownerKind: "protocol",
    label: "Base OptimismPortal",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x99c9fc46f92e8a1c0dec1b1747d010903e884be1",
    sourceRef: "optimism-bridge",
    category: "bridge",
    ownerName: "Optimism",
    ownerKind: "protocol",
    label: "Optimism L1StandardBridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xbeb5fc579115071764c7423a4f12edde41f106ed",
    sourceRef: "optimism-portal",
    category: "bridge",
    ownerName: "Optimism",
    ownerKind: "protocol",
    label: "Optimism Portal",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x8315177ab297ba92a06054ce80a67ed4dbd7ed3a",
    sourceRef: "arbitrum-bridge",
    category: "bridge",
    ownerName: "Arbitrum One",
    ownerKind: "protocol",
    label: "Arbitrum One Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa10c7ce4b876998858b1a9e12b10092229539400",
    sourceRef: "arbitrum-delayed-inbox",
    category: "bridge",
    ownerName: "Arbitrum One",
    ownerKind: "protocol",
    label: "Arbitrum One DelayedInbox",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa0c68c638235ee32657e8f720a23cec1bfc77c77",
    sourceRef: "polygon-bridge",
    category: "bridge",
    ownerName: "Polygon",
    ownerKind: "protocol",
    label: "Polygon PoS Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf",
    sourceRef: "polygon-erc20-bridge",
    category: "bridge",
    ownerName: "Polygon",
    ownerKind: "protocol",
    label: "Polygon ERC20 Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x32400084c286cf3e17e7b677ea9583e60a000324",
    sourceRef: "zksync-era-bridge",
    category: "bridge",
    ownerName: "zkSync Era",
    ownerKind: "protocol",
    label: "zkSync Era Diamond Proxy",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xd19d4b5d358258f05d7b411e21a1460d11b0876f",
    sourceRef: "linea-bridge",
    category: "bridge",
    ownerName: "Linea",
    ownerKind: "protocol",
    label: "Linea L1 Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6774bcbd5cecef1336b5300fb5186a12ddd8b367",
    sourceRef: "scroll-bridge",
    category: "bridge",
    ownerName: "Scroll",
    ownerKind: "protocol",
    label: "Scroll Messenger",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xb5a5f22694352c15b00323844ad545abb2b11028",
    sourceRef: "icon-bridge",
    category: "bridge",
    ownerName: "ICON",
    ownerKind: "protocol",
    label: "ICON Bridge",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x8eb8a3b98659cce290402893d0123abb75e3ab28",
    sourceRef: "avalanche-bridge",
    category: "bridge",
    ownerName: "Avalanche",
    ownerKind: "protocol",
    label: "Avalanche Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x3ee18b2214aff97000d974cf647e7c347e8fa585",
    sourceRef: "wormhole-token-bridge",
    category: "bridge",
    ownerName: "Wormhole",
    ownerKind: "protocol",
    label: "Wormhole Token Bridge",
    notes: "Cross-chain bridge — drained for $325M Feb 2022 (Solana side); current ETH-side contract.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x8731d54e9d02c286767d56ac03e8037c07e01e98",
    sourceRef: "stargate-router",
    category: "bridge",
    ownerName: "Stargate (LayerZero)",
    ownerKind: "protocol",
    label: "Stargate Router",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x66a71dcef29a0ffbdbe3c6a460a3b5bc225cd675",
    sourceRef: "layerzero-endpoint-v1",
    category: "bridge",
    ownerName: "LayerZero",
    ownerKind: "protocol",
    label: "LayerZero Endpoint v1",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x88dcdc47d2f83a99cf0000fdf667a468bb958a78",
    sourceRef: "mantle-l1-bridge",
    category: "bridge",
    ownerName: "Mantle",
    ownerKind: "protocol",
    label: "Mantle L1 Bridge",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x697402166fbf2f22e970df8a6486ef171dbfc524",
    sourceRef: "blast-bridge",
    category: "bridge",
    ownerName: "Blast",
    ownerKind: "protocol",
    label: "Blast L1 Bridge",
    confidence: 95,
  },

  // ============================================================
  // WALLET DRAINER GROUPS — Drainer-as-a-Service (DaaS) operators
  // that lease phishing infrastructure to affiliates and take a cut
  // of stolen funds. Every address below carries an Etherscan public
  // label ("Pink Drainer: Wallet 1", "Inferno Drainer", etc.) — the
  // strongest available off-chain attribution short of an OFAC
  // listing. Confidence 95.
  // ============================================================
  {
    chain: "ethereum",
    address: "0x63605e53d422c4f1ac0e01390ac59aaf84c44a51",
    sourceRef: "pink-drainer-wallet-1",
    category: "scam",
    ownerName: "Pink Drainer",
    ownerKind: "criminal-group",
    label: "Pink Drainer: Wallet 1",
    notes: "DaaS operator active 2023-2024. ScamSniffer attributed ~$75M+ across 20k+ victims before announced shutdown 2024-Q2. Known for impersonating journalists and hijacking Discord/Twitter accounts (incl. OpenAI CTO, Orbiter Finance).",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x00001f78189be22c3498cff1b8e02272c3220000",
    sourceRef: "inferno-drainer-main",
    category: "scam",
    ownerName: "Inferno Drainer",
    ownerKind: "criminal-group",
    label: "Inferno Drainer",
    notes: "DaaS operator that drained ~$80M+ from 100k+ victims 2022-2023. Announced shutdown Nov 2023; reloaded variant tracked by Check Point Research 2025. Affiliates kept 70-80% / Inferno took 20-30%.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0000daf60a1becf1bd617c584dea964455890000",
    sourceRef: "inferno-drainer-phishing-2",
    category: "scam",
    ownerName: "Inferno Drainer",
    ownerKind: "criminal-group",
    label: "Inferno Drainer: Phishing Contract 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xfb4d3eb37bde8fa4b52c60aabe55b3cd9908ec73",
    sourceRef: "inferno-drainer-2-ens",
    category: "scam",
    ownerName: "Inferno Drainer",
    ownerKind: "criminal-group",
    label: "inferno-drainer-2.eth",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0000553f880ffa3728b290e04e819053a3590000",
    sourceRef: "inferno-drainer-4-ens",
    category: "scam",
    ownerName: "Inferno Drainer",
    ownerKind: "criminal-group",
    label: "inferno-drainer-4.eth",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x412f10aad96fd78da6736387e2c84931ac20313f",
    sourceRef: "angel-drainer-412f",
    category: "scam",
    ownerName: "Angel Drainer",
    ownerKind: "criminal-group",
    label: "Angel Drainer: 0x412f",
    notes: "DaaS successor to Inferno Drainer (Nov 2023+). Upgraded to AngelX Sep 2024 — deployed 300+ phishing dApps in 4 days. Accounted for ~42% of drainer losses in Q1-Q2 2024 per ScamSniffer.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0000c3ace9e31a26ce1870d418cb045d73b30000",
    sourceRef: "angel-drainer-phishing-3",
    category: "scam",
    ownerName: "Angel Drainer",
    ownerKind: "criminal-group",
    label: "Angel Drainer: Phishing Contract 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0000626d6dc72989e3809920c67d01a7fe030000",
    sourceRef: "angel-drainer-phishing-9",
    category: "scam",
    ownerName: "Angel Drainer",
    ownerKind: "criminal-group",
    label: "Angel Drainer: Phishing Contract 9",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x9fc8265f2b376084423a1a348a89ecd894a9d106",
    sourceRef: "monkey-drainer-ens",
    category: "scam",
    ownerName: "Monkey Drainer",
    ownerKind: "criminal-group",
    label: "monkey-drainer.eth",
    notes: "One of the earliest DaaS operators (late 2022). Drained ~$13M before announcing retirement 2023-03-01 after CertiK doxxed at least one operator. Venom Drainer believed to be successor toolkit.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xaa336c6c9d11fa74eae5625467fd095c31bd1129",
    sourceRef: "venom-drainer-eth-pool",
    category: "scam",
    ownerName: "Venom Drainer",
    ownerKind: "criminal-group",
    label: "VenomDrainerr: ETH Pool",
    notes: "Successor toolkit to Monkey Drainer. Drained ~$27.5M starting Feb 2023 per Cointelegraph / ScamSniffer.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xa5e4b451d0a3c3d05fc3a8076fda45952b8f4f83",
    sourceRef: "pink-drainer-0xa5e4",
    category: "scam",
    ownerName: "Pink Drainer",
    ownerKind: "criminal-group",
    label: "Pink Drainer: 0xa5e4",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x85c4ff99bf0ecb24e02921b0d4b5d336523fa085",
    sourceRef: "fixedfloat-drainer",
    category: "scam",
    ownerName: "FixedFloat Drainer",
    ownerKind: "criminal-group",
    label: "FixedFloat Drainer",
    notes: "Cluster linked to the Feb 2024 FixedFloat exchange exploit (~$26M in BTC/ETH). Attributed to Lazarus by ZachXBT and Match Systems.",
    confidence: 95,
  },

  // ============================================================
  // VERIFIED HACK EXPLOITERS — 2022-2024 incidents where Etherscan
  // carries an explicit "X Exploiter" / "X Hacker" public label.
  // Distinct from the older block below: each entry is sourced from
  // Etherscan's labelcloud directly rather than inferred from press
  // coverage. Confidence 95.
  // ============================================================
  {
    chain: "ethereum",
    address: "0xadbab4f38ff9dcd71886f43b148bcad4a3081fb9",
    sourceRef: "mango-markets-eisenberg",
    category: "hack-source",
    ownerName: "Avraham Eisenberg",
    ownerKind: "individual",
    label: "ponzishorter.eth (Mango Markets exploiter)",
    notes: "$116M Mango Markets oracle-manipulation exploit 2022-10-11. Eisenberg returned $67M via DAO settlement; 2024 criminal convictions vacated by Judge Subramanian 2025-05.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xb1c33b391c2569b737ec387e731e88589e8ec148",
    sourceRef: "curve-2023-crv-eth-exploit",
    category: "hack-source",
    ownerName: "Curve Finance Exploiter",
    ownerKind: "criminal-group",
    label: "Curve Finance: CRV/ETH Exploit",
    notes: "$69M total losses across Curve factory pools 2023-07-30 via Vyper compiler bug (versions 0.2.15/0.2.16/0.3.0) defeating non-reentrancy guards. ~$12.7M of stolen funds later returned.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xfe3f568d58919b14aff72bd3f14e6f55bec6c4e0",
    sourceRef: "stake-com-hacker-funder",
    category: "hack-source",
    ownerName: "Stake.com Hack (Lazarus, Sep 2023)",
    ownerKind: "criminal-group",
    label: "Stake.com Hacker (initial)",
    notes: "$41M Stake.com exploit 2023-09-04. FBI attributed to DPRK Lazarus / APT38.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x94f1b9b64e2932f6a2db338f616844400cd58e8a",
    sourceRef: "stake-com-hacker-1",
    category: "hack-source",
    ownerName: "Stake.com Hack (Lazarus, Sep 2023)",
    ownerKind: "criminal-group",
    label: "Stake.com Hacker 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x3130662aece32f05753d00a7b95c0444150bcd3c",
    sourceRef: "stake-com-hacker-2",
    category: "hack-source",
    ownerName: "Stake.com Hack (Lazarus, Sep 2023)",
    ownerKind: "criminal-group",
    label: "Stake.com Hacker",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xba36735021a9ccd7582ebc7f70164794154ff30e",
    sourceRef: "stake-com-hacker-3",
    category: "hack-source",
    ownerName: "Stake.com Hack (Lazarus, Sep 2023)",
    ownerKind: "criminal-group",
    label: "Stake.com Hacker 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x7d84d78bb9b6044a45fa08b7fe109f2c8648ab4e",
    sourceRef: "stake-com-hacker-4",
    category: "hack-source",
    ownerName: "Stake.com Hack (Lazarus, Sep 2023)",
    ownerKind: "criminal-group",
    label: "Stake.com Hacker 4",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xd151050d43c28690766f50ce9ea8686c5d243a40",
    sourceRef: "playdapp-exploiter-1",
    category: "hack-source",
    ownerName: "PlayDapp Exploit",
    ownerKind: "criminal-group",
    label: "PlayDapp Exploiter",
    notes: "$290M PlayDapp double-exploit 2024-02-09 / 2024-02-12. Private key compromise allowed minting 1.79B PLA; ~$32M converted before scattering.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x1cae9eaa76e880fe47a26dd838e5ec056c289155",
    sourceRef: "playdapp-exploiter-2",
    category: "hack-source",
    ownerName: "PlayDapp Exploit",
    ownerKind: "criminal-group",
    label: "PlayDapp Exploiter 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x6e8836f050a315611208a5cd7e228701563d09c5",
    sourceRef: "munchables-exploiter",
    category: "hack-source",
    ownerName: "Munchables Exploit",
    ownerKind: "criminal-group",
    label: "Munchables Exploiter",
    notes: "$62.5M Munchables (Blast L2 GameFi) exploit 2024-03-26 by rogue developer suspected DPRK. Private keys returned; ~$60.5M recovered.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x04b21735e93fa3f8df70e2da89e6922616891a88",
    sourceRef: "wazirx-exploiter-1",
    category: "hack-source",
    ownerName: "WazirX Hack (Lazarus, July 2024)",
    ownerKind: "criminal-group",
    label: "WazirX Exploiter",
    notes: "$234.9M WazirX multisig hack 2024-07-18. Liminal Custody compromise; attributed to DPRK Lazarus by Crystal Intelligence and Elliptic.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x35febc10112302e0d69f35f42cce85816f8745ca",
    sourceRef: "wazirx-exploiter-2",
    category: "hack-source",
    ownerName: "WazirX Hack (Lazarus, July 2024)",
    ownerKind: "criminal-group",
    label: "WazirX Exploiter 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x90ca792206ed7ee9bc9da0d0df981fc5619f91fd",
    sourceRef: "wazirx-exploiter-3",
    category: "hack-source",
    ownerName: "WazirX Hack (Lazarus, July 2024)",
    ownerKind: "criminal-group",
    label: "WazirX Exploiter 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x75497999432b8701330fb68058bd21918c02ac59",
    sourceRef: "coinex-stake-shared-exploiter",
    category: "hack-source",
    ownerName: "CoinEx / Stake / Alphapo (Lazarus)",
    ownerKind: "criminal-group",
    label: "CoinEx Exploiter (shared with Stake.com/Alphapo)",
    notes: "$54M CoinEx hack 2023-09-12. Same address tagged Stake Exploiter on Polygon — Lazarus reuse error linked CoinEx, Stake.com (Sep 2023), and Alphapo (Jul 2023) per SlowMist/ZachXBT.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0a5984f86200415894821bfefc1c1de036dbf9e7",
    sourceRef: "poloniex-hacker-1",
    category: "hack-source",
    ownerName: "Poloniex Hack (Lazarus, Nov 2023)",
    ownerKind: "criminal-group",
    label: "Poloniex Hacker 1",
    notes: "$126M Poloniex hack 2023-11-10 (ETH/TRON/BTC). Justin Sun pledged 5% bounty; attributed to Lazarus.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x9e3b8da544bbacb7a7f5284dc9c2aff111180efd",
    sourceRef: "poloniex-hacker-9",
    category: "hack-source",
    ownerName: "Poloniex Hack (Lazarus, Nov 2023)",
    ownerKind: "criminal-group",
    label: "Poloniex Hacker 9",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x3e944000f1e31c0e244d36cda3f983066603fdfd",
    sourceRef: "poloniex-hacker-20",
    category: "hack-source",
    ownerName: "Poloniex Hack (Lazarus, Nov 2023)",
    ownerKind: "criminal-group",
    label: "Poloniex Hacker 20",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xfc146d1caf6ba1d1ce6dcb5b35dcbf895f50b0c4",
    sourceRef: "heco-bridge-exploiter",
    category: "hack-source",
    ownerName: "HECO Bridge / HTX Exploit",
    ownerKind: "criminal-group",
    label: "HECO Bridge Exploiter",
    notes: "$87M HECO Bridge + ~$12M HTX hot-wallet drain 2023-11-22. Suspected private-key compromise of Justin Sun operator account.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x5a22f867dfcb4f32d25a5fa365b9d9d78d5515dc",
    sourceRef: "htx-hot-wallet-attacker",
    category: "hack-source",
    ownerName: "HECO Bridge / HTX Exploit",
    ownerKind: "criminal-group",
    label: "HTX Hot Wallet Attacker",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xc0eb7e6e2b94aa43bdd0c60e645fe915d5c6eb84",
    sourceRef: "penpie-exploiter",
    category: "hack-source",
    ownerName: "Penpie Reentrancy Exploit",
    ownerKind: "criminal-group",
    label: "Penpiexyz Exploiter 2",
    notes: "$27M Penpie reentrancy exploit 2024-09-03 on Arbitrum/Ethereum via valueless SY tokens. Funded via Tornado Cash; refused to return funds.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xae4a7cde7c99fb98b0d5fa414aa40f0300531f43",
    sourceRef: "sonne-finance-exploiter",
    category: "hack-source",
    ownerName: "Sonne Finance Exploit",
    ownerKind: "criminal-group",
    label: "Sonne Finance Exploiter (EOA)",
    notes: "$20M Sonne Finance exploit 2024-05-14 on Optimism. Compound v2 fork zero-supply donation attack — 25-minute drain in WETH/VELO/soVELO/USDC.e.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xded2b1a426e1b7d415a40bcad44e98f47181dda2",
    sourceRef: "hedgey-finance-exploiter",
    category: "hack-source",
    ownerName: "Hedgey Finance Exploit",
    ownerKind: "criminal-group",
    label: "Hedgey Finance Exploiter",
    notes: "$44.7M Hedgey Finance exploit 2024-04-19 ($42.6M Arbitrum + $2.1M Ethereum). ClaimCampaigns approval-reuse via createLockedCampaign().",
    confidence: 95,
  },

  // ============================================================
  // BYBIT $1.4B HACK — Feb 21 2025, attributed to DPRK Lazarus
  // via Safe{Wallet} developer machine compromise. 401,347 ETH
  // drained from cold wallet. Largest crypto theft ever recorded.
  // Etherscan maintains 50+ exploiter sub-labels; entries below
  // are the primary collection wallets.
  // ============================================================
  {
    chain: "ethereum",
    address: "0x47666fab8bd0ac7003bce3f5c3585383f09486e2",
    sourceRef: "bybit-exploiter-1",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 1",
    notes: "$1.4B Bybit cold-wallet hack 2025-02-21. Lazarus compromised a Safe{Wallet} dev workstation and spoofed the multisig approval UI.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa4b2fd68593b6f34e51cb9edb66e71c1b4ab449e",
    sourceRef: "bybit-exploiter-2",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x36ed3c0213565530c35115d93a80f9c04d94e4cb",
    sourceRef: "bybit-exploiter-3",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 3",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x1542368a03ad1f03d96d51b414f4738961cf4443",
    sourceRef: "bybit-exploiter-4",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 4",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xdd90071d52f20e85c89802e5dc1ec0a7b6475f92",
    sourceRef: "bybit-exploiter-5",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 5",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x30a822cdd2782d2b2a12a08526452e885978fa1d",
    sourceRef: "bybit-exploiter-7",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 7",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x140c9ab92347734641b1a7c124ffdee58c20c3e3",
    sourceRef: "bybit-exploiter-10",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 10",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x4571bd67d14280e40bf3910bd39fbf60834f900a",
    sourceRef: "bybit-exploiter-54",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit Exploiter 54",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6dfc34609a05bc22319fa4cce1d1e2929548c0d7",
    sourceRef: "alphapo-1",
    category: "hack-source",
    ownerName: "Alphapo Hack (Lazarus, July 2023)",
    ownerKind: "criminal-group",
    label: "AlphaPo 1",
    notes: "~$60M Alphapo (web3 casino payment processor) hot-wallet drain 2023-07-22 across ETH/BTC/TRX. Hot wallet private-key leak; ZachXBT linked to Lazarus.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x040a96659fd7118259ebcd547771f6ecb9580d17",
    sourceRef: "alphapo-2",
    category: "hack-source",
    ownerName: "Alphapo Hack (Lazarus, July 2023)",
    ownerKind: "criminal-group",
    label: "Alphapo Drain 0x040a",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x52e86988bd07447c596e9b0c7765f8500113104c",
    sourceRef: "mixin-network-exploiter-1",
    category: "hack-source",
    ownerName: "Mixin Network Hack (Sep 2023)",
    ownerKind: "criminal-group",
    label: "Mixin Network Exploiter 1",
    notes: "~$200M Mixin Network breach 2023-09-23 (cloud provider DB compromise). Received 60k ETH (~$94M). Mixin offered $20M bug bounty for return.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x3b5fb9d9da3546e9ce6e5aa3cceca14c8d20041e",
    sourceRef: "mixin-network-exploiter-2",
    category: "hack-source",
    ownerName: "Mixin Network Hack (Sep 2023)",
    ownerKind: "criminal-group",
    label: "Mixin Network Exploiter (USDT→DAI)",
    notes: "Handled the ~$23.5M USDT leg; swapped to DAI to avoid freeze.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xb5d631a74ad9c9efcf96d6e9e2fabcb75c67eafa",
    sourceRef: "mixin-network-exploiter-3",
    category: "hack-source",
    ownerName: "Mixin Network Hack (Sep 2023)",
    ownerKind: "criminal-group",
    label: "Mixin Network Exploiter (ETH dispersal)",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xf7e8033366166f92eb477b7b38e0d47d47b43326",
    sourceRef: "bingx-exploiter-1",
    category: "hack-source",
    ownerName: "BingX Hack (Sep 2024)",
    ownerKind: "criminal-group",
    label: "BingX Exploiter 1",
    notes: "~$44.7M BingX hot-wallet hack 2024-09-19. Drained across ETH/Polygon/Optimism/BSC; on-chain pattern suggests Lazarus per Cyvers/SlowMist.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xf26e64ef4300ca027d2ffedd7d765d7a3906091c",
    sourceRef: "bingx-exploiter-6",
    category: "hack-source",
    ownerName: "BingX Hack (Sep 2024)",
    ownerKind: "criminal-group",
    label: "BingX Exploiter 6",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x63dc352ddfc17aa04edac47ce36e186c1e54b02c",
    sourceRef: "bingx-exploiter-8",
    category: "hack-source",
    ownerName: "BingX Hack (Sep 2024)",
    ownerKind: "criminal-group",
    label: "BingX Exploiter 8",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xcfc14fa81226074036622976d95897ff84b58d66",
    sourceRef: "bingx-exploiter-10",
    category: "hack-source",
    ownerName: "BingX Hack (Sep 2024)",
    ownerKind: "criminal-group",
    label: "BingX Exploiter 10",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xb0a2e43d3e0dc4c71346a71484ac6a2627bbcbed",
    sourceRef: "indodax-exploiter-1",
    category: "hack-source",
    ownerName: "Indodax Hack (Sep 2024)",
    ownerKind: "criminal-group",
    label: "Indodax Exploiter 1",
    notes: "~$25M Indodax hot-wallet hack 2024-09-10 across ETH/TRX/BTC/MATIC. Indonesia's largest CEX. Suspected Lazarus per ZachXBT.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x59101e532bc728599a2d373fcdc7aff58cb48df8",
    sourceRef: "indodax-exploiter-2",
    category: "hack-source",
    ownerName: "Indodax Hack (Sep 2024)",
    ownerKind: "criminal-group",
    label: "Indodax Exploiter 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x50275e0b7261559ce1644014d4b78d4aa63be836",
    sourceRef: "kyberswap-exploiter-1",
    category: "hack-source",
    ownerName: "KyberSwap Elastic Exploit",
    ownerKind: "criminal-group",
    label: "KyberSwap Exploiter 1",
    notes: "$48M KyberSwap Elastic exploit 2023-11-22 (multi-chain). NOTE: supersedes the older 'kyber-2023-hack' entry above, which carried an incorrect address.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xc9b826bad20872eb29f9b1d8af4befe8460b50c6",
    sourceRef: "kyberswap-exploiter-2",
    category: "hack-source",
    ownerName: "KyberSwap Elastic Exploit",
    ownerKind: "criminal-group",
    label: "KyberSwap Exploiter 2",
    notes: "Front-run / copycat exploiter; extracted ~$5.7M on Polygon and Avalanche.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x841ddf093f5188989fa1524e7b893de64b421f47",
    sourceRef: "uwu-lend-exploiter",
    category: "hack-source",
    ownerName: "UwU Lend Exploit",
    ownerKind: "criminal-group",
    label: "UwU Lend Exploiter",
    notes: "$19.4M UwU Lend oracle-manipulation exploit 2024-06-10 via Curve sUSDe pool. Followed by a second $3.7M exploit 2024-06-13.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xb5f798096bd4d969466e2284bda01f7a51049d3a",
    sourceRef: "m2-exchange-eoa-1",
    category: "hack-source",
    ownerName: "M2 Exchange Hack",
    ownerKind: "criminal-group",
    label: "M2 Exchange Drainer EOA",
    notes: "$13.7M M2 Exchange (UAE-licensed CEX) hot-wallet hack 2024-10-31 across ETH/BTC/SOL. M2 reimbursed user funds in full from corporate treasury.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x968b6984cba14444f23ee51be90652408155e142",
    sourceRef: "m2-exchange-eoa-2",
    category: "hack-source",
    ownerName: "M2 Exchange Hack",
    ownerKind: "criminal-group",
    label: "M2 Exchange Drainer EOA 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x24354d31bc9d90f62fe5f2454709c32049cf866b",
    sourceRef: "cream-flash-loan-3",
    category: "hack-source",
    ownerName: "Cream Finance Flash Loan Exploit",
    ownerKind: "criminal-group",
    label: "Cream Finance Flash Loan Exploiter 3",
    notes: "$130M Cream Finance flash loan exploit 2021-10-27. Third-largest DeFi hack at the time. Funds still being moved years later per Etherscan watchers.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x921760e71fb58dcc8de902ce81453e9e3d7fe253",
    sourceRef: "cream-flash-loan-2",
    category: "hack-source",
    ownerName: "Cream Finance Flash Loan Exploit",
    ownerKind: "criminal-group",
    label: "Cream Finance Flash Loan Exploiter 2",
    confidence: 95,
  },

  // ============================================================
  // HISTORICAL DEFI EXPLOITS (2020-2023) — older incidents with
  // long Etherscan labelcloud presence. Useful for trace work that
  // follows funds across half a decade of laundering.
  // ============================================================
  {
    chain: "ethereum",
    address: "0x148426fdc4c8a51b96b4bed827907b5fa6491ad0",
    sourceRef: "bzx-exploiter-1-feb2020",
    category: "hack-source",
    ownerName: "bZx Oracle Exploit (Feb 2020)",
    ownerKind: "criminal-group",
    label: "bZx Exploiter 1",
    notes: "First mainnet flash-loan attack on a DeFi protocol — Feb 2020 oracle manipulation. ~$1M across two attacks 2020-02-14 and 2020-02-18. Set the template for every flash-loan exploit since.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xb8c6ad5fe7cb6cc72f2c4196dca11fbb272a8cbf",
    sourceRef: "bzx-exploiter-2-feb2020",
    category: "hack-source",
    ownerName: "bZx Oracle Exploit (Feb 2020)",
    ownerKind: "criminal-group",
    label: "bZx Exploiter 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0acc0e5faa09cb1976237c3a9af3d3d4b2f35fa5",
    sourceRef: "bzx-privkey-2-nov2021",
    category: "hack-source",
    ownerName: "bZx Private Key Compromise (Nov 2021)",
    ownerKind: "criminal-group",
    label: "bZx PrivKey Exploiter 2",
    notes: "Separate ~$55M Nov 2021 bZx hack via developer private key phish — distinct incident from the Feb 2020 oracle attacks above.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x967bb571f0fc9ee79c892abf9f99233aa1737e31",
    sourceRef: "bzx-privkey-3-nov2021",
    category: "hack-source",
    ownerName: "bZx Private Key Compromise (Nov 2021)",
    ownerKind: "criminal-group",
    label: "bZx PrivKey Exploiter 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xafad9352eb6bcd085dd68268d353d0ed2571af89",
    sourceRef: "bzx-privkey-5-nov2021",
    category: "hack-source",
    ownerName: "bZx Private Key Compromise (Nov 2021)",
    ownerKind: "criminal-group",
    label: "bZx PrivKey Exploiter 5",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xcacf2d28b2a5309e099f0c6e8c60ec3ddf656642",
    sourceRef: "bonqdao-exploiter",
    category: "hack-source",
    ownerName: "BonqDAO Oracle Manipulation",
    ownerKind: "criminal-group",
    label: "BonqDAO Exploiter",
    notes: "$120M+ notional drain 2023-02-02 (Polygon). Cheap Tellor oracle update (10 TRB ≈ $175 stake) let attacker mint 100M BEUR + 120M wALBT against manipulated collateral.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x3dabf5e36df28f6064a7c5638d0c4e01539e35f1",
    sourceRef: "orion-protocol-exploiter-1",
    category: "hack-source",
    ownerName: "Orion Protocol Reentrancy",
    ownerKind: "criminal-group",
    label: "Orion Protocol Exploiter",
    notes: "~$3M Orion Protocol reentrancy 2023-02-02 (ETH + BNB). Double-credit token transfers via malicious pair contracts.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x837962b686fd5a407fb4e5f92e8be86a230484bd",
    sourceRef: "orion-protocol-exploiter-2",
    category: "hack-source",
    ownerName: "Orion Protocol Reentrancy",
    ownerKind: "criminal-group",
    label: "Orion Protocol Exploiter 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x085bdff2c522e8637d4154039db8746bb8642bff",
    sourceRef: "onyx-exploiter-1",
    category: "hack-source",
    ownerName: "Onyx Protocol Empty-Pool Exploit",
    ownerKind: "criminal-group",
    label: "Onyx Protocol Exploiter",
    notes: "$2.1M Onyx Protocol exploit 2023-11-01 — classic Compound v2 fork empty-pool attack against an unfunded PEPE market.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x4c9c8661243e9e9a15a35b8873317eb881330c98",
    sourceRef: "onyx-exploiter-2",
    category: "hack-source",
    ownerName: "Onyx Protocol Empty-Pool Exploit",
    ownerKind: "criminal-group",
    label: "Onyx Protocol Exploiter 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x5083956303a145f70ba9f3d80c5e6cb5ac842706",
    sourceRef: "onyx-exploiter-3",
    category: "hack-source",
    ownerName: "Onyx Protocol Empty-Pool Exploit",
    ownerKind: "criminal-group",
    label: "Onyx Protocol Exploiter 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x70285a11489bed93686410ebc727057cafb8129d",
    sourceRef: "tapioca-dao-exploiter",
    category: "hack-source",
    ownerName: "Tapioca DAO Hack (DPRK, Oct 2024)",
    ownerKind: "criminal-group",
    label: "Tapioca DAO Exploiter",
    notes: "$4.4M Tapioca DAO compromise 2024-10-18 via social-engineering of an engineer (malware). Token vesting contract takeover; 30M TAP minted. Protocol counter-exploited to recover 996 ETH. Attributed to a DPRK group.",
    confidence: 95,
  },

  // ============================================================
  // SOLANA DRAINER GROUPS — first non-EVM cluster on the graph.
  // Solscan public labels are noisier than Etherscan's, so we
  // anchor on Mandiant / Google Cloud Threat Intelligence and
  // Chainalysis attributions rather than the explorer alone.
  // ============================================================
  {
    chain: "solana",
    address: "B8Y1dERnVNoUUXeXA4NaCHiB9htcukMSkfHrFsTMHA7h",
    sourceRef: "clinksink-drainer-daas",
    category: "scam",
    ownerName: "CLINKSINK Drainer",
    ownerKind: "criminal-group",
    label: "CLINKSINK Drainer (DaaS collector)",
    notes: "Solana DaaS toolkit active since Dec 2023; 35+ affiliate campaigns. Address attributed to the DaaS operator by Mandiant / Google Cloud Threat Intelligence Jan 2024.",
    confidence: 90,
  },

  // ============================================================
  // MAJOR HACK INCIDENTS (extended) — high-graph-value nodes that
  // typically connect into mixers, exchanges, and bridges.
  // ============================================================
  // kyber-2023-hack entry removed: address 0x489a8756... did not
  // match Etherscan's "KyberSwap Exploiter" label. Correct addresses
  // (Exploiter 1 + 2) are attributed above in the VERIFIED HACK
  // EXPLOITERS section.
  {
    chain: "ethereum",
    address: "0x6b6c47c2c34d1c2c5f3c0c4dc8a5c34c3a1f7a96",
    sourceRef: "radiant-2024-hack",
    category: "hack-source",
    ownerName: "Radiant Capital Exploit",
    ownerKind: "criminal-group",
    label: "Radiant Capital $50M Hack (Lazarus)",
    notes: "$50M Radiant Capital exploit 2024-10-17, attributed to DPRK Lazarus by chain-analysis firms.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xeb6680ce69f95c3aff8f5d0b8b4f9b85b48d8c52",
    sourceRef: "badgerdao-2021-hack",
    category: "hack-source",
    ownerName: "BadgerDAO UI Exploit",
    ownerKind: "criminal-group",
    label: "BadgerDAO $120M Hack",
    notes: "$120M front-end injection exploit drained user approvals 2021-12-01.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6f1cdb3b8cffd07c0bcd7d3c10f4dc9e6a2c9b2e",
    sourceRef: "multichain-2023-collapse",
    category: "hack-source",
    ownerName: "Multichain Anyswap Collapse",
    ownerKind: "criminal-group",
    label: "Multichain $1.5B Drainer",
    notes: "$1.5B+ across multiple chains drained 2023-07 after CEO arrest in China; user funds never recovered.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x6354e79f21b56c11f48bcd7c451be456d7102a36",
    sourceRef: "harmony-horizon-2022",
    category: "hack-source",
    ownerName: "Harmony Horizon Bridge Exploit",
    ownerKind: "criminal-group",
    label: "Harmony Horizon $100M Hack (Lazarus)",
    notes: "$100M Harmony Horizon Bridge exploit 2022-06-23. Attributed to Lazarus by FBI and TRM Labs.",
    confidence: 100,
  },
  // Atomic Wallet 2023 entry removed: the address 0x098b716b... is
  // already attributed (correctly) above as "Ronin Bridge Hacker
  // (DPRK Lazarus)". No verified Atomic Wallet exploiter address has
  // been Etherscan-labeled — Lazarus dispersed proceeds across many
  // short-lived wallets. Re-add via a community submission when a
  // primary-source attribution surfaces.
  {
    chain: "ethereum",
    address: "0x7f268357a8c2552623316e2562d90e642bb538e5",
    sourceRef: "opensea-rate-limit-bug",
    category: "hack-destination",
    ownerName: "OpenSea 'Listing Bug' Sniper",
    ownerKind: "individual",
    label: "OpenSea Inactive-Listing Exploiter",
    notes: "Sniped delisted-but-still-active OpenSea offers Jan 2022; OpenSea reimbursed users ~$1.8M.",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x161112c2667aa4ed53b50edd6b8df40ed4f3c45d",
    sourceRef: "playmates-rug-2023",
    category: "scam",
    ownerName: "Various Rug-Pull Operators",
    ownerKind: "criminal-group",
    label: "Generic Rug Pull Operator (placeholder)",
    notes: "Placeholder — replace with documented rug-pull addresses on next curator pass.",
    confidence: 50,
  },
  {
    chain: "ethereum",
    address: "0x098b716b8aaf21512996dc57eb0615e2383e2f97",
    sourceRef: "lazarus-cluster-2024",
    category: "hack-destination",
    ownerName: "Lazarus Group (DPRK)",
    ownerKind: "criminal-group",
    label: "Lazarus Group Tornado-deposit cluster",
    notes: "Composite address representing DPRK-affiliated wallets known to deposit into mixers. Subject to OFAC sanctions.",
    confidence: 80,
  },

  // ============================================================
  // ADDITIONAL EXCHANGES — second-tier CEX + EU/Asia coverage
  // ============================================================
  // crypto-com-3 entry removed: duplicate of crypto-com-2 above
  // (both at 0x46340b20...feb9758).
  {
    chain: "ethereum",
    address: "0x4862733b5fddfd35f35ea8ccf08f5045e57388b3",
    sourceRef: "bitstamp-1",
    category: "exchange",
    ownerName: "Bitstamp",
    ownerKind: "exchange",
    label: "Bitstamp Hot 1",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x000000005736775feb0c8568e7dee77222a26880",
    sourceRef: "robinhood-1",
    category: "exchange",
    ownerName: "Robinhood",
    ownerKind: "exchange",
    label: "Robinhood Hot Wallet",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x9696f59e4d72e237be84ffd425dcad154bf96976",
    sourceRef: "binance-us-1",
    category: "exchange",
    ownerName: "Binance.US",
    ownerKind: "exchange",
    label: "Binance.US Hot 1",
    confidence: 90,
  },
];

export function curatedClaims(): AttributionClaim[] {
  const now = new Date();
  return CURATED_ADDRESSES.map((entry) => ({
    ...entry,
    source: "rexintel-curated",
    reportedAt: now,
    sourceUrl:
      entry.label && entry.chain === "ethereum"
        ? `https://etherscan.io/address/${entry.address}`
        : entry.chain === "bitcoin"
          ? `https://mempool.space/address/${entry.address}`
          : null,
  }));
}
