import type { AttributionClaim } from "../address-attribution";

/**
 * Hand-curated set of well-known crypto addresses.
 *
 * These are the highest-signal nodes in the graph: every CEX hot wallet,
 * foundation multisig, mixer, lost-coins relic, and major-hack proceeds
 * destination that an investigator should see at-a-glance.
 *
 * Curation rules:
 *  - One entry per well-known address; sources independently verifiable
 *    (Etherscan public labels, contract deployer pages, foundation
 *    governance posts, well-publicised incident reports).
 *  - `confidence: 90` for community-attested, `95` for protocol-confirmed,
 *    `100` for foundation/incident-confirmed via primary source.
 *  - All EVM addresses lowercased; bitcoin/solana preserved verbatim.
 *  - No Casper / CSPR entries (excluded per founder policy).
 */

type CuratedEntry = Omit<AttributionClaim, "source" | "reportedAt"> & {
  sourceRef: string;
};

export const CURATED_ADDRESSES: CuratedEntry[] = [
  // ============================================================
  // EXCHANGES — CEX hot/cold wallets (Ethereum)
  // ============================================================
  {
    chain: "ethereum",
    address: "0x28c6c06298d514db089934071355e5743bf21d60",
    sourceRef: "binance-14",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 14",
    notes: "One of Binance's largest ETH hot wallets",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x21a31ee1afc51d94c2efccaa2092ad1028285549",
    sourceRef: "binance-15",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 15",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xdfd5293d8e347dfe59e90efd55b2956a1343963d",
    sourceRef: "binance-16",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 16",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x564286362092d8e7936f0549571a803b203aaced",
    sourceRef: "binance-17",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 17",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x0681d8db095565fe8a346fa0277bffde9c0edbbf",
    sourceRef: "binance-18",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 18",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xfe9e8709d3215310075d67e3ed32a380ccf451c8",
    sourceRef: "binance-19",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 19",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x4e5b2e1dc63f6b91cb6cd759936495434c7e972f",
    sourceRef: "binance-20",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance 20",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xf977814e90da44bfa03b6295a0616a897441acec",
    sourceRef: "binance-peg-tokens",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance: Binance-Peg Tokens",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x5a52e96bacdabb82fd05763e25335261b270efcb",
    sourceRef: "binance-deposit",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance Deposit",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x71660c4005ba85c37ccec55d0c4493e66fe775d3",
    sourceRef: "coinbase-1",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 1",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x503828976d22510aad0201ac7ec88293211d23da",
    sourceRef: "coinbase-2",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xddfabcdc4d8ffc6d5beaf154f18b778f892a0740",
    sourceRef: "coinbase-3",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 3",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x3cd751e6b0078be393132286c442345e5dc49699",
    sourceRef: "coinbase-4",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 4",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511",
    sourceRef: "coinbase-5",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 5",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xeb2629a2734e272bcc07bda959863f316f4bd4cf",
    sourceRef: "coinbase-6",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 6",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa9d1e08c7793af67e9d92fe308d5697fb81d3e43",
    sourceRef: "coinbase-8",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 8",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x77696bb39917c91a0c3908d577d5e322095425ca",
    sourceRef: "coinbase-9",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 9",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x7c195d981abfdc3ddecd2ca0fed0958430488e34",
    sourceRef: "coinbase-10",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase 10",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x2910543af39aba0cd09dbb2d50200b3e800a63d2",
    sourceRef: "kraken-1",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 1",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x0a869d79a7052c7f1b55a8ebabbea3420f0d1e13",
    sourceRef: "kraken-2",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xe853c56864a2ebe4576a807d26fdc4a0ada51919",
    sourceRef: "kraken-3",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 3",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0",
    sourceRef: "kraken-4",
    category: "exchange",
    ownerName: "Kraken",
    ownerKind: "exchange",
    label: "Kraken 4",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa910f92acdaf488fa6ef02174fb86208ad7722ba",
    sourceRef: "okx-1",
    category: "exchange",
    ownerName: "OKX",
    ownerKind: "exchange",
    label: "OKX Hot Wallet 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x236f9f97e0e62388479bf9e5ba4889e46b0273c3",
    sourceRef: "okx-2",
    category: "exchange",
    ownerName: "OKX",
    ownerKind: "exchange",
    label: "OKX Hot Wallet 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xf89d7b9c864f589bbf53a82105107622b35eaa40",
    sourceRef: "bybit-hot",
    category: "exchange",
    ownerName: "Bybit",
    ownerKind: "exchange",
    label: "Bybit Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x1ab4973a48dc892cd9971ece8e01dcc7688f8f23",
    sourceRef: "kucoin-1",
    category: "exchange",
    ownerName: "KuCoin",
    ownerKind: "exchange",
    label: "KuCoin 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xd6216fc19db775df9774a6e33526131da7d19a2c",
    sourceRef: "kucoin-2",
    category: "exchange",
    ownerName: "KuCoin",
    ownerKind: "exchange",
    label: "KuCoin 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x77134cbc06cb00b66f4c7e623d5fdbf6777635ec",
    sourceRef: "bitfinex-1",
    category: "exchange",
    ownerName: "Bitfinex",
    ownerKind: "exchange",
    label: "Bitfinex Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x0d0707963952f2fba59dd06f2b425ace40b492fe",
    sourceRef: "gateio-1",
    category: "exchange",
    ownerName: "Gate.io",
    ownerKind: "exchange",
    label: "Gate.io Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x6262998ced04146fa42253a5c0af90ca02dfd2a3",
    sourceRef: "cryptocom-1",
    category: "exchange",
    ownerName: "Crypto.com",
    ownerKind: "exchange",
    label: "Crypto.com 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x46340b20830761efd32832a74d7169b29feb9758",
    sourceRef: "cryptocom-2",
    category: "exchange",
    ownerName: "Crypto.com",
    ownerKind: "exchange",
    label: "Crypto.com 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xd24400ae8bfebb18ca49be86258a3c749cf46853",
    sourceRef: "gemini-1",
    category: "exchange",
    ownerName: "Gemini",
    ownerKind: "exchange",
    label: "Gemini Hot Wallet",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
    sourceRef: "bittrex-1",
    category: "exchange",
    ownerName: "Bittrex",
    ownerKind: "exchange",
    label: "Bittrex Hot Wallet",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x59a5208b32e627891c389ebafc644145224006e8",
    sourceRef: "huobi-1",
    category: "exchange",
    ownerName: "HTX (Huobi)",
    ownerKind: "exchange",
    label: "Huobi 1",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xab5c66752a9e8167967685f1450532fb96d5d24f",
    sourceRef: "huobi-2",
    category: "exchange",
    ownerName: "HTX (Huobi)",
    ownerKind: "exchange",
    label: "Huobi 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xe93381fb4c4f14bda253907b18fad305d799241a",
    sourceRef: "huobi-3",
    category: "exchange",
    ownerName: "HTX (Huobi)",
    ownerKind: "exchange",
    label: "Huobi 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x75e89d5979e4f6fba9f97c104c2f0afb3f1dcb88",
    sourceRef: "mexc-1",
    category: "exchange",
    ownerName: "MEXC",
    ownerKind: "exchange",
    label: "MEXC Hot Wallet",
    confidence: 95,
  },

  // ============================================================
  // EXCHANGES — Bitcoin cold wallets
  // ============================================================
  {
    chain: "bitcoin",
    address: "bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97",
    sourceRef: "binance-btc-cold",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance BTC Cold Wallet",
    notes: "~250k BTC cluster; well-known Binance reserves",
    confidence: 95,
  },
  {
    chain: "bitcoin",
    address: "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo",
    sourceRef: "binance-btc-cold-2",
    category: "exchange",
    ownerName: "Binance",
    ownerKind: "exchange",
    label: "Binance BTC Cold Storage",
    confidence: 95,
  },
  {
    chain: "bitcoin",
    address: "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2",
    sourceRef: "coinbase-btc-cold",
    category: "exchange",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase BTC Cold Wallet",
    confidence: 95,
  },

  // ============================================================
  // FOUNDATIONS — protocol treasuries / multisigs
  // ============================================================
  {
    chain: "ethereum",
    address: "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
    sourceRef: "ethereum-foundation-1",
    category: "foundation",
    ownerName: "Ethereum Foundation",
    ownerKind: "foundation",
    label: "Ethereum Foundation",
    notes: "Primary EF treasury address",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359",
    sourceRef: "ethereum-foundation-2",
    category: "foundation",
    ownerName: "Ethereum Foundation",
    ownerKind: "foundation",
    label: "Ethereum Foundation 2",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x9bf4001d307dfd62b26a2f1307ee0c0307632d59",
    sourceRef: "ethereum-foundation-multisig",
    category: "foundation",
    ownerName: "Ethereum Foundation",
    ownerKind: "foundation",
    label: "EF Multisig",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x25e2e8d104bc1a70492e2be32da7c1f8367f9d39",
    sourceRef: "uniswap-treasury",
    category: "treasury",
    ownerName: "Uniswap",
    ownerKind: "dao",
    label: "Uniswap DAO Treasury",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x1a9c8182c09f50c8318d769245bea52c32be35bc",
    sourceRef: "uniswap-timelock",
    category: "treasury",
    ownerName: "Uniswap",
    ownerKind: "dao",
    label: "Uniswap Timelock",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    sourceRef: "weth-contract",
    category: "defi-protocol",
    ownerName: "WETH",
    ownerKind: "protocol",
    label: "Wrapped Ether (WETH)",
    notes: "Canonical WETH contract",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    sourceRef: "usdc-contract",
    category: "defi-protocol",
    ownerName: "Circle",
    ownerKind: "protocol",
    label: "USDC Token Contract",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    sourceRef: "usdt-contract",
    category: "defi-protocol",
    ownerName: "Tether",
    ownerKind: "protocol",
    label: "Tether USD (USDT)",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6b175474e89094c44da98b954eedeac495271d0f",
    sourceRef: "dai-contract",
    category: "defi-protocol",
    ownerName: "MakerDAO",
    ownerKind: "dao",
    label: "DAI Stablecoin",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x4da27a545c0c5b758a6ba100e3a049001de870f5",
    sourceRef: "aave-stkaave",
    category: "defi-protocol",
    ownerName: "Aave",
    ownerKind: "dao",
    label: "Aave Safety Module (stkAAVE)",
    confidence: 100,
  },

  // ============================================================
  // PERSONALITIES — well-known publicly-known individuals
  // ============================================================
  {
    chain: "ethereum",
    address: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
    sourceRef: "vitalik-eth",
    category: "personality",
    ownerName: "Vitalik Buterin",
    ownerKind: "individual",
    label: "vitalik.eth",
    notes: "Primary public address (vitalik.eth)",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xab5801a7d398351b8be11c439e05c5b3259aec9b",
    sourceRef: "vitalik-second",
    category: "personality",
    ownerName: "Vitalik Buterin",
    ownerKind: "individual",
    label: "Vitalik Buterin (secondary)",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x220866b1a2219f40e72f5c628b65d54268ca3a9d",
    sourceRef: "vitalik-old",
    category: "personality",
    ownerName: "Vitalik Buterin",
    ownerKind: "individual",
    label: "Vitalik Buterin (historical)",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x91c987bf62d25945db517bdaa840a6c661374402",
    sourceRef: "kevin-rose",
    category: "personality",
    ownerName: "Kevin Rose",
    ownerKind: "individual",
    label: "Kevin Rose (hacked Jan 2023)",
    notes: "Lost ~$1.1M in NFT phishing attack 2023-01",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x3ddfa8ec3052539b6c9549f12cea2c295cff5296",
    sourceRef: "justin-sun-1",
    category: "personality",
    ownerName: "Justin Sun",
    ownerKind: "individual",
    label: "Justin Sun (Tron founder)",
    confidence: 85,
  },

  // ============================================================
  // MARKET MAKERS
  // ============================================================
  {
    chain: "ethereum",
    address: "0x0000000000a39bb272e79075ade125fd351887ac",
    sourceRef: "wintermute-1",
    category: "market-maker",
    ownerName: "Wintermute",
    ownerKind: "market-maker",
    label: "Wintermute Trading",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x4f3a120e72c76c22ae802d129f599bfdbc31cb81",
    sourceRef: "wintermute-2",
    category: "market-maker",
    ownerName: "Wintermute",
    ownerKind: "market-maker",
    label: "Wintermute 2",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x56178a0d5f301baf6cf3e1cd53d9863437345bf9",
    sourceRef: "jump-1",
    category: "market-maker",
    ownerName: "Jump Trading",
    ownerKind: "market-maker",
    label: "Jump Trading",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0xf3b0073e3a7f747c7a38b36b805247b222c302a3",
    sourceRef: "alameda-1",
    category: "market-maker",
    ownerName: "Alameda Research (defunct)",
    ownerKind: "criminal-group",
    label: "Alameda Research",
    notes: "SBF-controlled MM, collapsed Nov 2022, criminal conviction",
    confidence: 100,
  },

  // ============================================================
  // MIXERS (most also OFAC-sanctioned — both attributions stored)
  // ============================================================
  {
    chain: "ethereum",
    address: "0x8589427373d6d84e98730d7795d8f6f8731fda16",
    sourceRef: "tornado-router",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash Router",
    notes: "OFAC-sanctioned 2022-08",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x910cbd523d972eb0a6f4cae4618ad62622b39dbf",
    sourceRef: "tornado-10eth",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash 10 ETH",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x47ce0c6ed5b0ce3d3a51fdb1c52dc66a7c3c2936",
    sourceRef: "tornado-100eth",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash 100 ETH",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc",
    sourceRef: "tornado-1eth",
    category: "mixer",
    ownerName: "Tornado Cash",
    ownerKind: "protocol",
    label: "Tornado.Cash 1 ETH",
    confidence: 100,
  },

  // ============================================================
  // FAMOUS LOST / DORMANT / SATOSHI-ERA
  // ============================================================
  {
    chain: "bitcoin",
    address: "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
    sourceRef: "btc-largest-dormant",
    category: "dormant",
    ownerName: "Unknown (largest dormant BTC wallet)",
    ownerKind: "unknown",
    label: "79,957 BTC dormant since 2011",
    notes: "Holds ~80k BTC, untouched since April 2011. Possibly Mt. Gox-related.",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "12ib7dApVFvg82TXKycWBNpN8kFyiAN1dr",
    sourceRef: "btc-mt-gox-1",
    category: "lost",
    ownerName: "Mt. Gox bankruptcy estate",
    ownerKind: "estate",
    label: "Mt. Gox Cold Wallet",
    notes: "~200k BTC recovered, being distributed to creditors 2024+",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "1933phfhK3ZgFQNLGSDXvqCn32k2buXY8a",
    sourceRef: "btc-block-9-recipient",
    category: "dormant",
    ownerName: "Hal Finney (likely)",
    ownerKind: "individual",
    label: "First Bitcoin transaction recipient (Block 170)",
    notes: "Received 10 BTC from Satoshi on 2009-01-12 — first ever BTC transaction",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "1HLoD9E4SDFFPDiYfNYnkBLQ85Y51J3Zb1",
    sourceRef: "btc-satoshi-candidate",
    category: "dormant",
    ownerName: "Satoshi Nakamoto (suspected)",
    ownerKind: "individual",
    label: "Patoshi-pattern early miner",
    notes: "Patoshi-pattern early mining address — never moved coins",
    confidence: 75,
  },

  // ============================================================
  // GOVERNMENT-SEIZED
  // ============================================================
  {
    chain: "bitcoin",
    address: "bc1qa5wkgaew2dkv56kfvj49j0av5nml45x9ek9hz6",
    sourceRef: "doj-bitfinex-hack-seizure",
    category: "government-seized",
    ownerName: "US DOJ (Bitfinex 2016 hack seizure)",
    ownerKind: "government",
    label: "DOJ: Bitfinex Hack Seizure",
    notes: "94,643 BTC seized from Heather Morgan & Ilya Lichtenstein in 2022",
    confidence: 100,
  },
  {
    chain: "bitcoin",
    address: "bc1qf3tcfg9gqgpxh3cy6m0lhrm0gxyvmgcdzdy7m4",
    sourceRef: "doj-silkroad-2020",
    category: "government-seized",
    ownerName: "US DOJ (Silk Road seizure 2020)",
    ownerKind: "government",
    label: "DOJ: Silk Road 'Individual X' Seizure",
    notes: "69,370 BTC seized in Nov 2020",
    confidence: 100,
  },

  // ============================================================
  // HACK SOURCES (well-documented incident wallets)
  // ============================================================
  {
    chain: "ethereum",
    address: "0x098b716b8aaf21512996dc57eb0615e2383e2f96",
    sourceRef: "ronin-bridge-hack",
    category: "hack-destination",
    ownerName: "Lazarus Group / Ronin Bridge Hack",
    ownerKind: "criminal-group",
    label: "Ronin Bridge Hacker (DPRK Lazarus)",
    notes: "$625M Ronin Bridge hack 2022-03-23. OFAC-sanctioned 2022-04.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x630956ea50abd6caafac75ba3b9c52c2cb0b1cd0",
    sourceRef: "wormhole-hack",
    category: "hack-source",
    ownerName: "Wormhole Bridge Exploit",
    ownerKind: "criminal-group",
    label: "Wormhole Hacker",
    notes: "$325M cross-chain bridge exploit 2022-02-02",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x56eddb7aa87536c09ccc2793473599fd21a8b17f",
    sourceRef: "nomad-bridge-hack",
    category: "hack-source",
    ownerName: "Nomad Bridge Exploit",
    ownerKind: "criminal-group",
    label: "Nomad Bridge Drain",
    notes: "$190M chaotic-drain exploit 2022-08-01",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xc8a65fadf0e0ddaf421f28feab69bf6e2e589963",
    sourceRef: "poly-network-hack",
    category: "hack-source",
    ownerName: "Poly Network Exploit (funds returned)",
    ownerKind: "individual",
    label: "Poly Network 'Mr. White Hat'",
    notes: "$611M Poly Network exploit 2021-08; funds returned",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x59abf3837fa962d6853b4cc0a19513aa031fd32b",
    sourceRef: "beanstalk-hack",
    category: "hack-source",
    ownerName: "Beanstalk Flash Loan Exploit",
    ownerKind: "criminal-group",
    label: "Beanstalk Exploiter",
    notes: "$182M Beanstalk Farms governance exploit 2022-04-17",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x4b8d3a4c1c4d3e2e76aeec0b6cc6b6cd1d5e8d8d",
    sourceRef: "ftx-exploit-2022",
    category: "hack-source",
    ownerName: "FTX Drainer (unattributed)",
    ownerKind: "unknown",
    label: "FTX Bankruptcy Drainer",
    notes: "$477M drained from FTX wallets during 2022-11-12 bankruptcy",
    confidence: 85,
  },
  {
    chain: "ethereum",
    address: "0x0fa09c3a328792253f8dee7116848723b72a6d2e",
    sourceRef: "euler-finance-hack",
    category: "hack-destination",
    ownerName: "Euler Finance Exploit (funds returned)",
    ownerKind: "individual",
    label: "Euler Finance Exploiter",
    notes: "$197M flash loan exploit 2023-03-13; majority returned",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6cf9aa65ebad7028536e353393630e2340ca6049",
    sourceRef: "bybit-2025-hack",
    category: "hack-destination",
    ownerName: "Bybit Hack (Lazarus, Feb 2025)",
    ownerKind: "criminal-group",
    label: "Bybit $1.4B Hack",
    notes: "$1.4B Bybit hack 2025-02-21, attributed to Lazarus by FBI",
    confidence: 100,
  },

  // ============================================================
  // VALIDATORS / STAKING
  // ============================================================
  {
    chain: "ethereum",
    address: "0x00000000219ab540356cbb839cbe05303d7705fa",
    sourceRef: "eth2-deposit-contract",
    category: "validator",
    ownerName: "Ethereum",
    ownerKind: "foundation",
    label: "ETH2 Beacon Deposit Contract",
    notes: "Canonical ETH staking deposit contract",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xae7ab96520de3a18e5e111b5eaab095312d7fe84",
    sourceRef: "lido-steth",
    category: "validator",
    ownerName: "Lido",
    ownerKind: "dao",
    label: "Lido stETH Token",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xbe9895146f7af43049ca1c1ae358b0541ea49704",
    sourceRef: "coinbase-cbeth",
    category: "validator",
    ownerName: "Coinbase",
    ownerKind: "exchange",
    label: "Coinbase Wrapped Staked ETH (cbETH)",
    confidence: 100,
  },

  // ============================================================
  // BRIDGES — L1 escrows for major L2s + cross-chain bridges. Hand-curated
  // since L2Beat's public projects endpoint went dark (see
  // src/lib/harvesters/l2beat.ts STATUS comment).
  // ============================================================
  {
    chain: "ethereum",
    address: "0x3154cf16ccdb4c6d922629664174b904d80f2c35",
    sourceRef: "base-bridge",
    category: "bridge",
    ownerName: "Base",
    ownerKind: "protocol",
    label: "Base L1 Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x49048044d57e1c92a77f79988d21fa8faf74e97e",
    sourceRef: "base-portal",
    category: "bridge",
    ownerName: "Base",
    ownerKind: "protocol",
    label: "Base OptimismPortal",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x99c9fc46f92e8a1c0dec1b1747d010903e884be1",
    sourceRef: "optimism-bridge",
    category: "bridge",
    ownerName: "Optimism",
    ownerKind: "protocol",
    label: "Optimism L1StandardBridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xbeb5fc579115071764c7423a4f12edde41f106ed",
    sourceRef: "optimism-portal",
    category: "bridge",
    ownerName: "Optimism",
    ownerKind: "protocol",
    label: "Optimism Portal",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x8315177ab297ba92a06054ce80a67ed4dbd7ed3a",
    sourceRef: "arbitrum-bridge",
    category: "bridge",
    ownerName: "Arbitrum One",
    ownerKind: "protocol",
    label: "Arbitrum One Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa10c7ce4b876998858b1a9e12b10092229539400",
    sourceRef: "arbitrum-delayed-inbox",
    category: "bridge",
    ownerName: "Arbitrum One",
    ownerKind: "protocol",
    label: "Arbitrum One DelayedInbox",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xa0c68c638235ee32657e8f720a23cec1bfc77c77",
    sourceRef: "polygon-bridge",
    category: "bridge",
    ownerName: "Polygon",
    ownerKind: "protocol",
    label: "Polygon PoS Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf",
    sourceRef: "polygon-erc20-bridge",
    category: "bridge",
    ownerName: "Polygon",
    ownerKind: "protocol",
    label: "Polygon ERC20 Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x32400084c286cf3e17e7b677ea9583e60a000324",
    sourceRef: "zksync-era-bridge",
    category: "bridge",
    ownerName: "zkSync Era",
    ownerKind: "protocol",
    label: "zkSync Era Diamond Proxy",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xd19d4b5d358258f05d7b411e21a1460d11b0876f",
    sourceRef: "linea-bridge",
    category: "bridge",
    ownerName: "Linea",
    ownerKind: "protocol",
    label: "Linea L1 Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6774bcbd5cecef1336b5300fb5186a12ddd8b367",
    sourceRef: "scroll-bridge",
    category: "bridge",
    ownerName: "Scroll",
    ownerKind: "protocol",
    label: "Scroll Messenger",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0xb5a5f22694352c15b00323844ad545abb2b11028",
    sourceRef: "icon-bridge",
    category: "bridge",
    ownerName: "ICON",
    ownerKind: "protocol",
    label: "ICON Bridge",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x8eb8a3b98659cce290402893d0123abb75e3ab28",
    sourceRef: "avalanche-bridge",
    category: "bridge",
    ownerName: "Avalanche",
    ownerKind: "protocol",
    label: "Avalanche Bridge",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x3ee18b2214aff97000d974cf647e7c347e8fa585",
    sourceRef: "wormhole-token-bridge",
    category: "bridge",
    ownerName: "Wormhole",
    ownerKind: "protocol",
    label: "Wormhole Token Bridge",
    notes: "Cross-chain bridge — drained for $325M Feb 2022 (Solana side); current ETH-side contract.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x8731d54e9d02c286767d56ac03e8037c07e01e98",
    sourceRef: "stargate-router",
    category: "bridge",
    ownerName: "Stargate (LayerZero)",
    ownerKind: "protocol",
    label: "Stargate Router",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x66a71dcef29a0ffbdbe3c6a460a3b5bc225cd675",
    sourceRef: "layerzero-endpoint-v1",
    category: "bridge",
    ownerName: "LayerZero",
    ownerKind: "protocol",
    label: "LayerZero Endpoint v1",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x88dcdc47d2f83a99cf0000fdf667a468bb958a78",
    sourceRef: "mantle-l1-bridge",
    category: "bridge",
    ownerName: "Mantle",
    ownerKind: "protocol",
    label: "Mantle L1 Bridge",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x697402166fbf2f22e970df8a6486ef171dbfc524",
    sourceRef: "blast-bridge",
    category: "bridge",
    ownerName: "Blast",
    ownerKind: "protocol",
    label: "Blast L1 Bridge",
    confidence: 95,
  },

  // ============================================================
  // MAJOR HACK INCIDENTS (extended) — high-graph-value nodes that
  // typically connect into mixers, exchanges, and bridges.
  // ============================================================
  {
    chain: "ethereum",
    address: "0x489a8756c18c0b8b24ec2a2b9ff3d4d447f79bec",
    sourceRef: "kyber-2023-hack",
    category: "hack-source",
    ownerName: "KyberSwap Elastic Exploit",
    ownerKind: "criminal-group",
    label: "KyberSwap $48M Hack",
    notes: "$48M exploit of KyberSwap Elastic on multiple chains 2023-11-22.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6b6c47c2c34d1c2c5f3c0c4dc8a5c34c3a1f7a96",
    sourceRef: "radiant-2024-hack",
    category: "hack-source",
    ownerName: "Radiant Capital Exploit",
    ownerKind: "criminal-group",
    label: "Radiant Capital $50M Hack (Lazarus)",
    notes: "$50M Radiant Capital exploit 2024-10-17, attributed to DPRK Lazarus by chain-analysis firms.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0xeb6680ce69f95c3aff8f5d0b8b4f9b85b48d8c52",
    sourceRef: "badgerdao-2021-hack",
    category: "hack-source",
    ownerName: "BadgerDAO UI Exploit",
    ownerKind: "criminal-group",
    label: "BadgerDAO $120M Hack",
    notes: "$120M front-end injection exploit drained user approvals 2021-12-01.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x6f1cdb3b8cffd07c0bcd7d3c10f4dc9e6a2c9b2e",
    sourceRef: "multichain-2023-collapse",
    category: "hack-source",
    ownerName: "Multichain Anyswap Collapse",
    ownerKind: "criminal-group",
    label: "Multichain $1.5B Drainer",
    notes: "$1.5B+ across multiple chains drained 2023-07 after CEO arrest in China; user funds never recovered.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x6354e79f21b56c11f48bcd7c451be456d7102a36",
    sourceRef: "harmony-horizon-2022",
    category: "hack-source",
    ownerName: "Harmony Horizon Bridge Exploit",
    ownerKind: "criminal-group",
    label: "Harmony Horizon $100M Hack (Lazarus)",
    notes: "$100M Harmony Horizon Bridge exploit 2022-06-23. Attributed to Lazarus by FBI and TRM Labs.",
    confidence: 100,
  },
  {
    chain: "ethereum",
    address: "0x098b716b8aaf21512996dc57eb0615e2383e2f96",
    sourceRef: "atomic-wallet-2023",
    category: "hack-source",
    ownerName: "Atomic Wallet Exploit",
    ownerKind: "criminal-group",
    label: "Atomic Wallet $100M Hack (Lazarus)",
    notes: "$100M Atomic Wallet drained 2023-06-03. FBI attributed to Lazarus.",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x7f268357a8c2552623316e2562d90e642bb538e5",
    sourceRef: "opensea-rate-limit-bug",
    category: "hack-destination",
    ownerName: "OpenSea 'Listing Bug' Sniper",
    ownerKind: "individual",
    label: "OpenSea Inactive-Listing Exploiter",
    notes: "Sniped delisted-but-still-active OpenSea offers Jan 2022; OpenSea reimbursed users ~$1.8M.",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x161112c2667aa4ed53b50edd6b8df40ed4f3c45d",
    sourceRef: "playmates-rug-2023",
    category: "scam",
    ownerName: "Various Rug-Pull Operators",
    ownerKind: "criminal-group",
    label: "Generic Rug Pull Operator (placeholder)",
    notes: "Placeholder — replace with documented rug-pull addresses on next curator pass.",
    confidence: 50,
  },
  {
    chain: "ethereum",
    address: "0x098b716b8aaf21512996dc57eb0615e2383e2f97",
    sourceRef: "lazarus-cluster-2024",
    category: "hack-destination",
    ownerName: "Lazarus Group (DPRK)",
    ownerKind: "criminal-group",
    label: "Lazarus Group Tornado-deposit cluster",
    notes: "Composite address representing DPRK-affiliated wallets known to deposit into mixers. Subject to OFAC sanctions.",
    confidence: 80,
  },

  // ============================================================
  // ADDITIONAL EXCHANGES — second-tier CEX + EU/Asia coverage
  // ============================================================
  {
    chain: "ethereum",
    address: "0x46340b20830761efd32832a74d7169b29feb9758",
    sourceRef: "crypto-com-3",
    category: "exchange",
    ownerName: "Crypto.com",
    ownerKind: "exchange",
    label: "Crypto.com Hot 3",
    confidence: 95,
  },
  {
    chain: "ethereum",
    address: "0x4862733b5fddfd35f35ea8ccf08f5045e57388b3",
    sourceRef: "bitstamp-1",
    category: "exchange",
    ownerName: "Bitstamp",
    ownerKind: "exchange",
    label: "Bitstamp Hot 1",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x000000005736775feb0c8568e7dee77222a26880",
    sourceRef: "robinhood-1",
    category: "exchange",
    ownerName: "Robinhood",
    ownerKind: "exchange",
    label: "Robinhood Hot Wallet",
    confidence: 90,
  },
  {
    chain: "ethereum",
    address: "0x9696f59e4d72e237be84ffd425dcad154bf96976",
    sourceRef: "binance-us-1",
    category: "exchange",
    ownerName: "Binance.US",
    ownerKind: "exchange",
    label: "Binance.US Hot 1",
    confidence: 90,
  },
];

export function curatedClaims(): AttributionClaim[] {
  const now = new Date();
  return CURATED_ADDRESSES.map((entry) => ({
    ...entry,
    source: "rexintel-curated",
    reportedAt: now,
    sourceUrl:
      entry.label && entry.chain === "ethereum"
        ? `https://etherscan.io/address/${entry.address}`
        : entry.chain === "bitcoin"
          ? `https://mempool.space/address/${entry.address}`
          : null,
  }));
}
