/**
 * Run with: npx tsx scripts/seed-intel-casper-hackathon-expose.ts
 *
 * Inserts the Casper Hackathon 2026 investigative exposé as a featured
 * incident-class intel row at the top of /intel. Idempotent — matches on
 * the headline, so re-running updates the body without changing publicId
 * or breaking inbound links.
 *
 * Anonymous source by design (RexIntel publishes anonymously). The byline
 * renders as "Anonymous source" in the UI and "Rex Intel Services
 * (Anonymous source)" in the article JSON-LD.
 */
import "dotenv/config";
import { eq, sql } from "drizzle-orm";
import { db, submissions } from "../src/lib/db";
import type { IntelPayload } from "../src/lib/db/schema";

const HEADLINE =
  "Casper Hackathon 2026: the 3rd-place winner's deployer wallet was the bot operator that funded 106 voters";

const body = [
  // First paragraph = the public teaser (first ~280 chars when gated).
  // Lead with the strongest finding to convert wallet-signups.
  "On 21 January 2026, the Casper Association announced the winners of Casper Hackathon 2026 — a contest it publicly described as having \"Sybil resistance and full transparency.\" The on-chain record shows three things at once: the voter pool was bot-shaped, the bot operators were the winners, and the chain disagrees with the marketing.",
  "",
  "## The headline finding",
  "",
  "The 3rd-place winner of Casper Hackathon 2026 was a project called CasperLink, which received the $3,000 prize. CasperLink's own project documentation — `phase1.md` in the `SohamJuneja/CasperLink` repository on GitHub — names the project's owner wallet explicitly:",
  "",
  "```",
  "Account Hash (Owner):",
  "account-hash-74ab92cebdb16189b8a1d3ed5a87d6fff8df694e9ede46393b5e11bb441be597",
  "",
  "Public Key:",
  "02031ed02f6abebdec47e03f18bc1ee37fcae4d999e82a4f49512c8d25489dfd5302",
  "```",
  "",
  "That account hash is the same wallet that, on Casper mainnet, directly funded **106 voter wallets** in the FANR2 voting contract (`cbf2518437fbf7f8bdc895dad8eb1bcc5ea4fa0b7978b33721ea73366ad42428`) — the contract that recorded the hackathon's \"community vote.\" The wallet was first funded on-chain on 2026-01-15 at 22:07 UTC, eleven hours after the voting contract was deployed. Anyone with a Casper RPC and a few minutes can verify the wallet, its balance (~345 CSPR at the time of writing), and the 106 outgoing dust transfers that established its downstream voter cohort.",
  "",
  "The contest's announced 3rd-place team owned the wallet that funded the largest single cluster of voters in the contest's own ballot. The voter pool and the winning team were not separate populations.",
  "",
  "## What Casper said",
  "",
  "Casper's 5 February 2026 post-hackathon recap described the voting process as \"on-chain via CSPR.fans\" with \"Sybil resistance and full transparency.\" Casper's own announcement of the contest in late 2025 included an explicit prize-system table: $25,000 in cash plus $5,000 in NodeOps platform credits plus $10,000 in ChainGPT API grants = $40,000 total. Halborn Security, NodeOps, ChainGPT, and NOWNodes were all listed as co-sponsors on the official Final Round marketing banner.",
  "",
  "Casper marketed the contest as a community-decided event. The contest's official rules, published on DoraHacks at `dorahacks.io/hackathon/casper-hackathon-2026`, included a clause we'll call the Community Choice Fast-Track. The verbatim text:",
  "",
  "> Community Choice Fast-Track: The top 5 projects selected through community voting will also advance to the Final Round, even if they do not meet all technical expectations such as having a functional prototype, Testnet deployment, or GitHub repository.",
  "",
  "Projects with no working code, no testnet deployment, and no GitHub repo could advance to the finals by community vote alone. That was the design. The voting power was assigned by an off-chain Telegram mini-app (CSPR.fans) where users earned points by following Casper on Twitter, watching videos, downloading the wallet, and inviting friends — a referral-compounded point-farming system in which the Casper Association's own server decided who held how much voting weight. The on-chain contract minted new vote-tokens for any signed message the off-chain server authorized; there was no on-chain Sybil resistance because Sybil resistance is impossible in a model where the central authority signs the votes.",
  "",
  "Casper's own announcement of the contest also reserved the Casper Association's right to \"support any additional projects it deems valuable, including post-hackathon grants and incubation opportunities.\" The override of the community vote was disclosed in the marketing copy.",
  "",
  "**The submission deadline was extended mid-contest.** Casper's published rules — still visible on DoraHacks at the time of writing — show the original submission deadline of 4 January 2026 23:59 UTC struck through, replaced by an extended deadline of 11 January 2026 23:59 UTC. The rules-text strikethrough is in their own document. Late-arriving bot wallets benefited from the extra week; the apex bot-funder wallet that this piece centers on was first funded eleven hours after Round 2's voting contract was deployed on 15 January, so the extension specifically widened the window during which fresh wallets could still be qualified for the on-chain vote.",
  "",
  "**The sponsors lent their names to a security claim that the on-chain record falsifies.** Casper's Final Round marketing banner names four co-sponsors alongside the Casper Association: Halborn Security, NOWNodes, NodeOps, and ChainGPT. Halborn is a Web3 security firm; its logo on a contest publicly framed as \"Sybil-resistant and fully transparent\" was a credibility-stamp. We surface here, without assertion about Halborn's actual scope of work on this hackathon, that the on-chain record we present is incompatible with the Sybil-resistance claim the banner endorsed. NodeOps ($5,000 in compute credits), ChainGPT ($10,000 in API grants), and NOWNodes (CSPR Full Node / RPC access) each contributed prize value to a process whose voter pool was, by every measure we can run on Casper mainnet, scripted.",
  "",
  "## What the chain shows",
  "",
  "We pulled the complete record of the FANR2 voting contract: every deploy, every mint, every transfer, plus the wallet history of every voter and every project.",
  "",
  "**1,869 voting deploys. 751 unique voter wallets.**",
  "",
  "Of those 751 voters:",
  "",
  "- **67.2% (505)** had their first-ever on-chain deploy within 24 hours of their first vote. They came onto Casper specifically to vote.",
  "- **92.7% (696)** have not touched Casper since the hackathon ended. The community of voters didn't stay a community.",
  "- **52.3% (393)** cast exactly one vote and disappeared.",
  "- **91.1% of all mints (1,675 of 1,838)** are exactly 1,000 FANR2 — the official daily-cap value. The vast majority of voters max-allocated their entire daily ration to a single project rather than splitting across favorites the way a community member would.",
  "- **5.5% of voters (41 wallets) cast their first vote within 60 seconds of receiving their first CSPR.** The top 15 fastest fired within 24 to 44 seconds of being funded. That cadence is not human; it is a script funding a wallet and submitting a vote in the same automated loop.",
  "",
  "**The funding pyramid.** Of the 749 voters whose first incoming CSPR transfer we could trace, only 131 distinct upstream wallets funded them. The top 7 funders fed half the entire voter pool — 372 of 749. Tracing each voter five hops back through their funding chain, **fifteen apex wallets account for 96% of the voter base**. This is not a community. It is a distribution network.",
  "",
  "**The leaderboard-tip proof.** Per-project, we computed what fraction of each project's voters came from a single dominant funder cluster:",
  "",
  "- Project ranked 3rd in FANR2 received (account-hash `28f5f1a2…`): **55.9% of its 281 votes came from one funder's downstream voters** (`74ab92ce…` — the same wallet CasperLink names as its owner).",
  "- Project ranked 4th in FANR2 received (account-hash `066662e9…`): **61.6% of its 198 votes came from one other funder's downstream voters** (`41e4339e…`).",
  "- Project ranked 1st (account-hash `9842d06f…`): 59.5% of its 351 votes came from a single high-balance wallet whose pattern doesn't match an exchange withdrawal.",
  "",
  "Compare to the tail of the leaderboard: projects that received 3 to 5 votes each show 0–33% fresh-baked voters, 0–50% bot-funded voters, and natural funder diversity. The bottom of the leaderboard had organic community voters. The top of the leaderboard did not.",
  "",
  "**The Casper Association's own wallet.** The wallet that deployed the voting contract (`0bc9335b32b92985dd765680d3e058cf060efc1fba295f1b6342f58ea04f5d65` — the operational identity of CSPR.fans and the registrar of the `*.fans.cspr` Casper-domain registrations) directly funded 34 voter wallets with 535 CSPR. The same wallet seeded **4 of the 7 top-vote-receiving project shells** with first transfers of exactly 2.5 CSPR each. Three of those four shells (account hashes `4d47ac81…`, `066662e9…`, `ce509235…`) were funded by the Association in a six-second window on 2026-01-07 at 14:05 UTC — a clear scripted batch-spawn, not three independent project teams coincidentally configuring themselves identically. Casper Association funded both the voter pool and the recipient shells.",
  "",
  "## How CSPR.fans Sybil mechanics actually work, on-chain",
  "",
  "Casper's marketing said the vote was Sybil-resistant. CSPR.fans is the Telegram mini-app where, per the official rules, \"You'll be able to send up to 1,000 FAN points per day to your favorite project(s).\" Users earn those points by following Casper on X, watching YouTube videos, downloading the Casper Wallet, and inviting friends — referral-compounded. The mechanism we measured on-chain works like this:",
  "",
  "1. A user accumulates points off-chain on the CSPR.fans server (Casper Association controlled).",
  "2. The user signs a vote message authorizing N FANR2 to be minted to a chosen project; the CSPR.fans server countersigns with an Association-controlled key.",
  "3. The signed message is submitted on-chain as a deploy to the FANR2 voting contract.",
  "4. The contract verifies the signature against the Association's signing key and **mints new FANR2 tokens directly to the recipient project**. There is no balance debit on the voter side. There is no on-chain supply cap.",
  "",
  "Receipts:",
  "",
  "- **The FANR2 contract has 1,848 token-actions on record. 1,838 of them are mints (`from_hash: null`). Only 10 are transfers.** The contract is a mint-on-instruction machine. Voters never hold FANR2 balances; the vote is the mint, and the supply is whatever the Association's signing key authorizes.",
  "",
  "- **All 45 unique mint recipients are projects. Zero voters.** Confirmed by querying `/contract-packages/{hash}/ft-token-actions` and segmenting recipient addresses against the voter set and project set.",
  "",
  "- **Vote-signature uniformity.** Of 1,848 vote signatures examined, **1,847 (99.95%) share the same first byte (0x02 = secp256k1 indicator). One outlier signature uses 0x81.** Every vote was authorized by the same kind of Casper Association signing scheme; the system is structurally single-key.",
  "",
  "- **91.1% of all mints (1,675 of 1,838) are exactly 1,000 FANR2** — the official daily allocation cap. A community voter who genuinely supports multiple projects splits their daily 1,000 across favorites (500+300+200, etc.). 91% of voters in this contest max-allocated their entire daily ration to a single project. The other 9% — the only split-vote behavior in the dataset — is the closest thing to organic community voting we can isolate.",
  "",
  "- **The off-chain server stayed in real time.** Each deploy carries a sequential `vote_id` issued by the CSPR.fans server. We sorted all 1,859 successful on-chain votes by `vote_id` and by timestamp: only 2 are out-of-order (0.1%), and the mean rank divergence between issuance order and landing order is 0.1 positions. The off-chain server issued IDs and the operator submitted them on-chain immediately — a real-time scripted loop, not a batch-queued pre-issuance.",
  "",
  "- **21.7% of issued vote_ids never landed on-chain.** The `vote_id` range observed is 3,076 to 5,436 (span 2,360), but only 1,859 vote_ids actually appear in the on-chain record. The off-chain server authorized 512 votes (21.7%) that the corresponding wallet either failed to submit, let expire, or had rejected — a remediation gap consistent with the community's account that Casper \"suspended some points\" after fake accounts were flagged. The suspended votes did not retroactively void anything; the surviving votes still drove the announced leaderboard.",
  "",
  "- **The contract was upgraded mid-vote.** Contract version 1 (`241275992d67bc5a5b…`) was deployed at 2026-01-15T10:45:55Z when voting opened and recorded 840 votes. Five days later, at 2026-01-20T11:15:59Z — with voting still active — version 1 was disabled and version 2 (`818a6d3628ddf3b9d4…`) deployed; it recorded the remaining 1,029 votes. The mid-vote contract swap was visible on cspr.live to anyone watching the contract page, but it was not announced in the public hackathon timeline. The entry-point IDs change between versions, so any third party who was monitoring \"calls to entry_point 479564 of the voting contract\" stopped seeing votes after January 20 even though voting continued through January 25.",
  "",
  "- **The Casper Association wallet (`0bc9335b…`) operates with `deployment_threshold: 1` and `key_management_threshold: 1`.** A single private-key signature can authorize every action the Association's wallet takes on-chain — 75,196 deploys and 74,831 transfers across its history. There is no multi-sig requirement, no key rotation, no associated_keys redundancy. The same key that signs vote authorizations on CSPR.fans is the same key that can move funds, register `.fans.cspr` domains, deploy or disable contracts, and approve any other treasury action.",
  "",
  "These properties are not Sybil resistance. They are the opposite: a single off-chain decision-maker that signs whatever message gets paid for, with no on-chain supply constraint, no Sybil check that survives a wallet-spawn, no multi-sig protecting the signing authority, and a contract that can be — and was — modified mid-vote. The on-chain record cannot tell us who counts as a real voter because the off-chain database that makes that decision is private to the Casper Association.",
  "",
  "## How the operators avoided detection",
  "",
  "Reading the data, the operators were measurably sophisticated about hiding their footprints. We list the anti-detection patterns because they distinguish this from amateur hackathon farming and matter for anyone running a similar investigation on a future contest:",
  "",
  "- **No same-block voter clustering.** Casper mainnet produces roughly one block every 32 seconds. Across the 10-day voting window, 1,825 distinct blocks contained at least one FANR2 vote-deploy. Of those, only 29 blocks (1.6%) contained ≥2 distinct voters; **zero blocks contained 3+ distinct voters**. The largest single-block voter cluster was 2. A naive bot operator firing votes from a single machine would cluster many in the same block (mempool batching is the cheap default). The operators here paced their submissions to scatter across blocks — a deliberate anti-detection measure that costs operator time but makes mempool-level clustering analysis return nothing.",
  "",
  "- **No same-second batch voter funding.** For each of the 749 traced voters, we have the timestamp of their first incoming CSPR transfer. We bucketed by (funder, timestamp-to-the-second). **Zero buckets contained 2+ voters funded in the same second by the same sender.** The most obvious bot-spawn signature (one transaction funding many wallets) is absent — the operators funded each wallet via a separate transaction, paying the per-tx gas overhead in exchange for an audit that doesn't return a smoking gun on first-pass batch-funding analysis.",
  "",
  "- **Cascading peer-to-peer funding.** 481 of 749 voters (64.2%) were funded by a wallet that is itself a voter. Apex funder `74ab92ce…` voted, then funded 106 other voters. Apex funder `41e4339e…` voted, then funded 88 others. The operators built a multi-generation cascade — top wallet → mid-tier wallets → leaf voter wallets — so that no single \"bank\" wallet has the obvious shape of funding hundreds of voters. The on-chain pyramid we identified only resolves when you trace each voter four or five hops upstream.",
  "",
  "- **Realistic time-of-day distribution.** Hour-of-day UTC voting counts peak between 12:00–13:00 and 18:00–21:00 UTC, with the lowest activity at 02:00–04:00 UTC — consistent with the global daytime distribution of real human users. A naive bot would fire votes around the clock at off-peak hours; the operators here calibrated to match human activity patterns. The realistic timing distribution makes raw \"votes per hour\" histograms reveal nothing.",
  "",
  "These are the signatures of an operator who has done this before. The cross-hackathon prior-work we identified for the operator-cluster usernames — Polkadot hackathons, Solana hackathons, multi-chain submissions across 2023–2025 — is consistent with this skill level. The Casper Hackathon 2026 wasn't a first attempt.",
  "",
  "## 39 finalists, 46 vote-recipient shells",
  "",
  "DoraHacks reports 39 buidls in the Casper Hackathon 2026 Final Round. The FANR2 contract recorded votes flowing to 46 distinct project account-hashes. The difference (seven extra project-shells) is unaccounted for in the published finalist list.",
  "",
  "We don't have a single explanation for the discrepancy. Possible reads: some project entries used multiple Casper account-hashes (one for the team registration, one for the deployed contract, one for the demo); some are test deploys made by the Casper Association or by the operators themselves; one project shell in the vote data appears as a contract-package-hash reference (`hash-778b9d…`) rather than an account-hash, suggesting it was an automated or scripted entry rather than a standard team submission.",
  "",
  "Worth surfacing because the discrepancy means the on-chain vote distribution and the published finalist count don't reconcile. If you're trying to verify the announced results against the chain, you can't — the buckets don't match.",
  "",
  "## The Round 1 to Round 2 leaderboard didn't carry over",
  "",
  "A participant in the contest's Telegram channel wrote during the voting period: *\"going from first place with 2.5 million points to this in the second round is quite amusing.\"* Someone who led Round 1 (Qualification) with 2.5 million CSPR.fans points did not make the Round 2 (Final) winners' announcement.",
  "",
  "We were not able to locate the Round 1 voting contract on Casper mainnet. cspr.cloud's `/contract-packages?search=` endpoint, queried for \"Hackathon 2026 R1,\" \"FANR1,\" and similar terms, returned unrelated results (validator voting tokens, an NFT collection called \"The funnies,\" generic minting contracts). The Round 1 contract — if it was deployed on-chain at all, or whether the Qualification Round vote happened entirely off-chain — is one of the gaps in this investigation we have not been able to close. We surface the comment because the Round-1-leader-to-Round-2-loser transition, if real, is consistent with a Round 2 voter pool that didn't share the composition of Round 1.",
  "",
  "## Smoking guns, in order of weight",
  "",
  "### Gun 1 — CasperLink's deployer is the apex bot-funder",
  "",
  "The CasperLink team's GitHub repository, owned by GitHub user `SohamJuneja`, contains a file named `phase1.md` that documents the project's deployment. In that file, the team identifies its owner wallet by both account hash and public key, links to the testnet account page on `testnet.cspr.live`, and uses the wallet in their documented deployment workflow. The wallet, on Casper mainnet, is the wallet that funded 106 voters in the FANR2 contract.",
  "",
  "CasperLink was announced as the 3rd-place winner ($3,000). The same wallet the team named in their own README as the project's owner is the wallet that ran the largest single bot-voter cluster in the contest. The mainnet wallet has 212 deploys and 209 transfers — consistent with an active operator wallet that spent its 10-day life inside the hackathon window.",
  "",
  "We make no claim about whether the team intended this when they wrote the README. We note only what is publicly verifiable: the wallet they named is the wallet that funded the 106 voters; both facts are independently visible on `cspr.live` and `cspr.cloud`. The two facts are not separable.",
  "",
  "### Gun 2 — abdul-kabugu ran three competing entries with shared on-chain wallets",
  "",
  "Three different hackathon entries — `BridgeX-dapp/bridgeX` (the announced Interoperability winner, $2,500), `anchor-protoco/protocol`, and `Xayaan/Casper-FOMO` — reference the same Casper account-hashes in their respective repositories. `BridgeX` and `anchor-protoco` share three on-chain wallets in their code (pubkeys `02039daee9…`, `0202f5a92a…`, and account-hash `4e37642c85…`). `anchor-protoco` and `Casper-FOMO` share a fourth (`02036d9b88…`, balance ~471 CSPR).",
  "",
  "Independently, the commit author email `kabuguabdul2@gmail.com` appears in the commit logs of both `BridgeX-dapp/bridgeX` and `anchor-protoco/protocol`. The git history identifies the same hand on the keyboards of both repositories. The shared on-chain wallets confirm the same operator across all three entries.",
  "",
  "`anchor-protoco/protocol` is a six-commit repository whose first commit added 53,474 lines of code in a single push. `Casper-FOMO` has two commits made ten seconds apart and was never touched again. The same operator submitted: a serious-looking AI-generated codebase (BridgeX), a single-commit AI-codebase dump (anchor-protoco), and a 10-second submission abandon (Casper-FOMO). One of the three won an Interoperability prize.",
  "",
  "### Gun 3 — the 2nd-place winner is an active Casper Network core-repo contributor",
  "",
  "GitHub user `furkanahmetk`, owner of the `furkanahmetk/shroud-protocol` repository that won 2nd place in the Final Round ($7,000), made seven commits to `casper-network/casper-nctl` — Casper's official Network Control Tool — between 26 September and 17 October 2025. Each commit is signed off by `Furkan Ahmet Kara <furkanahmetkara.fk@gmail.com>` and the same email appears in the Shroud Protocol repo's commit log. The official contributions took place in the six weeks immediately before the hackathon launched on 14 November.",
  "",
  "Independently, the user `mertksk` is listed as a contributor on `furkanahmetk/shroud-protocol`, the winning Shroud Protocol repo. The same `mertksk` submitted their own competing entry, `mertksk/accelerate`, to the same hackathon. The commit author email `mert_ksk_1998@hotmail.com` is in both repos' commit logs. `furkanahmetk` and `mertksk` mutually follow each other on GitHub and co-authored a pre-hackathon repository named `furkanahmetk/accelerate` (created 2 December 2025) which `mertksk` also contributed to.",
  "",
  "Casper Hackathon 2026's announced 2nd-place winner is, by GitHub commit evidence, a long-time Casper-tooling contributor whose ongoing collaborator submitted a separate competing entry under their own name. A contributor to one entrant doesn't normally also enter as their own team in the same contest.",
  "",
  "### Gun 4 — the announced 1st-place winner is publicly identifiable as a Turkish developer named in the project's promotional X account",
  "",
  "We add this layer because the operator-cluster framing of the case rests on identifying who the operators are. The first-place team CasPay was hosted at `dmrdvn/caspay` — repo deleted; no Wayback snapshot. The GitHub account `dmrdvn` is publicly cross-referenced on LinkedIn as Demirdöven; the team's promotional X handle is `@elontaylor1` — an Anglo-sounding pseudonym we surface only because the gap between the project's marketing-persona handle and the operator's real identity is itself a pattern. Three of the four announced winners trace to operator identities concentrated in Turkey (CasPay/Demirdöven, Shroud Protocol/Furkan Ahmet Kara, plus Shroud Protocol contributor mertksk); a fourth traces to Bukoba, Tanzania (BridgeX/abdul-kabugu). Only one (CasperLink/SohamJuneja, India-based) sits outside the Turkey + Bukoba cluster — and that one is the case with the strongest single on-chain self-incrimination (the apex bot-funder wallet documented as the project's owner).",
  "",
  "### Gun 5 — the 1st-place winner's repo was deleted; its owner mutually follows an AI-tooling specialist",
  "",
  "CasPay, the announced 1st-place winner ($10,000), was hosted at the GitHub repository `dmrdvn/caspay`. The repository was deleted at some point after the hackathon. No Wayback Machine snapshot is available.",
  "",
  "`dmrdvn` is mutually followed on GitHub by `hcytmz` — the GitHub handle of a Turkey-based developer whose 251 public repositories are heavily concentrated on AI agentic-coding tooling: `claude-code`, `awesome-claude-skills`, `everything-claude-code`, `antigravity-kit`, `opencode`, `awesome-agent-skills`, `awesome-ai-agent-papers`, and similar. `hcytmz` is not listed as a contributor on any hackathon repository in our dataset, but the mutual-follow tie is the social-graph fingerprint that survived the repo deletion. The simplest reading consistent with the available evidence is that the CasPay codebase was generated using AI-agent tooling — the field `hcytmz` curates — and the repo was then deleted after the prize was claimed. We note the evidence; we acknowledge that a clean alternative — `hcytmz` and `dmrdvn` are friends with no project link — exists.",
  "",
  "### Gun 6 — CSPR Capital, a stablecoin project with no public code",
  "",
  "Casper's published Final Round line-up included a project called CSPR Capital. The project was promoted in the contest's Telegram channel as \"the first native stablecoin on Casper — backed 1:1 by overcollateralized CSPR.\" A native CSPR-backed stablecoin requires substantial smart contract code: a collateral vault, a minting and burning mechanism, oracle integration for the price feed, liquidation logic, governance hooks.",
  "",
  "The `cspr-capital` GitHub organization was registered on 2026-01-10 — one day before the (extended) submission deadline. The organization has four public repositories. **Zero of them are a Casper-named project.** The only Casper-related content on the org is a `.github` profile-readme created 2026-03-25, two months after the hackathon ended. No public smart-contract code. No frontend repo. No test suite. No README documenting the protocol.",
  "",
  "A stablecoin project that submitted to a hackathon explicitly requiring \"an on-chain component\" but published no public on-chain component is, by definition, missing the deliverable. Either the project is private (which would have been against the hackathon's open-source spirit and most contributors' expectations) or the project doesn't exist. Casper Hackathon 2026 listed it as a finalist anyway.",
  "",
  "### Gun 7 — KunBojiMan's hackathon entry is a 2021 Make Software codebase resubmitted with new commits on top",
  "",
  "The hackathon entry at `KunBojiMan/casper-php-sdk` claims to be a PHP SDK for the Casper Network. The commit history identifies its origin: the **initial commit was made on 2021-09-15 by the GitHub user `mssteuer`** — Michael Steuer, the CTO of Casper Network and co-founder of Make Software (the entity that operates CSPR.fans and cspr.live).",
  "",
  "The repository's pre-2025 commit history is dominated by Make Software employees: Michael Steuer (CTO, 2 commits 2021), Roman Bylbas (`RomanovSci`, 19 commits 2021–2025-01-23, email `roman@make.services`), Muhammet Kara (`mrkara`, 7 commits 2021–2022-02, email `muhammet@make.services`), and one other Make Software contributor named `ihor`. The codebase is, by its git history, a Make Software / Casper Foundation open-source library that has existed since 2021 and that the CTO personally created.",
  "",
  "The GitHub user `KunBojiMan` (account created 2022-06, well after `casper-php-sdk` was first committed) republished this 2021 codebase under their own organization in late 2025 and submitted it as their hackathon entry. The CTO's old commits travel in the cloned history but represent no involvement during the hackathon window. We make no claim that the CTO endorsed this submission or that `KunBojiMan` did anything illegal; the project is open-source-licensed and forks are permitted. We note only that the entry submitted under the team name `casper-php-sdk` in Casper Hackathon 2026 is structurally a years-old Casper Foundation SDK with new wrapping, not an original hackathon project.",
  "",
  "### Gun 8 — three different 'teams' hardcoded the same 5,036-CSPR wallet",
  "",
  "We cloned every alive hackathon-finalist repository (29 of 39 — eight had been deleted between the contest and this writing, two we couldn't locate) and grepped each tree for Casper-format addresses: secp256k1 public keys (`02[66hex]`), ed25519 public keys (`01[64hex]`), account hashes (`account-hash-[64hex]`), contract package hashes, URefs, and bare 64-hex strings appearing near Casper-context keywords. We deduplicated, then enriched every candidate against the cspr.cloud mainnet API. Of 532 candidate addresses, 39 resolved to real on-chain accounts.",
  "",
  "Of those 39, one cross-repository pattern is the story:",
  "",
  "The wallet `017d96b9a63abcb61c870a4f55187a…` (5,036 CSPR balance — not a placeholder, not a dust amount, a real funded account) appears hardcoded in the codebases of three different Casper Hackathon 2026 finalist entries:",
  "",
  "- `le-stagiaire-ag2r/Casper-projet` — a 685-commit, two-author, three-month real-shape development project from a French intern team",
  "- `SAHU-01/CasperStake` — a staking dApp submitted by a different developer (multi-hackathon prior history under that account)",
  "- `IHB1-Foundation/magni-cspr` — an IHB1 Foundation project (the `IHB1-Foundation` GitHub organization dates to August 2025)",
  "",
  "Three different team owners. Three different project entries. Three different repositories. One wallet, hardcoded in all three. The Casper docs and the Odra framework's example code use zero-balance placeholders or the all-zeros account-hash. A 5,036-CSPR wallet appearing in three different teams' code is not example-template behavior. The three plausible explanations:",
  "",
  "1. **A shared deployment service or faucet** — Casper-ecosystem infrastructure that three projects independently integrated with. We checked the wallet's transaction history; it does not match the dispersal pattern of a public faucet (a faucet's outgoing transfers would be a steady stream of small equal amounts to many different recipients — this wallet's history is not that shape).",
  "2. **Shared deployment infrastructure** — e.g. a hackathon-mentor or accelerator's deploy bot that several teams routed through. Plausible but not previously disclosed by Casper or any of the three teams.",
  "3. **Operator-cluster coordination** — three nominally-independent \"teams\" with overlapping operator backing. The strongest single signal in our broader dataset of operator clustering; the weakest direct proof at the wallet level for this particular wallet.",
  "",
  "We do not assert which of the three. The wallet sits in three teams' source repositories under the same hash, no team discloses a relationship with the other two, and no public Casper Association documentation explains why this would be a normal pattern.",
  "",
  "A separate lighter cross-reference for completeness: `furkanahmetk/shroud-protocol` (the announced 2nd-place winner) and `le-stagiaire-ag2r/Casper-projet` (the French intern project) both reference the wallet `0143345f0d7c6e8d1a8e70eecdc3b4…` (30 CSPR balance). The small balance is consistent with a shared faucet, a tutorial wallet, or a deployment-service account that several builders happened to route through. We log the cross-reference as a tie of unknown nature rather than treating it as operator-cluster evidence.",
  "",
  "### Gun 9 — one wallet seeded two different 'top-7' project shells 67 seconds apart",
  "",
  "The wallet `65a1bb912303cdaa01a7b07c9ad5bef91dbf45d6cd9d9f3dc69eecd3a8aebcca` funded the first incoming transfer to two different Casper Hackathon 2026 Final Round project shells with 2.5 CSPR each: `24df63ca…` (the 5th-highest-voted project) was funded at 2025-12-23T09:25:05Z, and `6b3559aa…` (the 6th-highest-voted project) was funded 67 seconds earlier at 2025-12-23T09:23:58Z. Same operator, two competing entries, both landing in the top tier of the contest's vote leaderboard.",
  "",
  "Unlike the abdul-kabugu cluster (where everything points at a serial multi-chain hackathon farmer running three entries from shared wallets), this funder profile is different: the wallet was created on-chain in July 2023 (2.5-year-old account), has 135 lifetime deploys, only ever funded 1 voter directly, and currently holds 8.2 CSPR (mostly drained). This is consistent with an established community member who entered two projects rather than an operator running a bot farm. We do not assert otherwise — but we surface it because the contest's prize structure assumed one team per submission, and the contest tolerated one wallet birthing two of its top-7 project shells in the same minute without disclosure on either side.",
  "",
  "### Gun 10 — 71 of one project's voters all withdrew from the same high-balance wallet",
  "",
  "Casper Hackathon 2026's announced 1st-place winner — CasPay, project shell `9842d06f78b91aee7a…` — received 351 of its votes in the FANR2 contract. **209 of those 351 votes (59.5%) came from voters whose first incoming CSPR transfer was from the same single wallet: `496d542527e1a29f576ab7c3f4c947bfcdc9b4145f75f6ec40e36089432d7351`.**",
  "",
  "On its face that wallet is consistent with a centralized exchange hot wallet: created May 2021 (5-year-old account), 91,371,460 CSPR balance (≈$91M class), 73,347 lifetime deploys, 106,110 lifetime transfers. Real CEX hot wallets do generate downstream voter cohorts during real on-chain events (people withdraw, then act). So one read of this finding is: the 1st-place winner had a large CEX-withdrawal user base that voted for it.",
  "",
  "The alternative read: a real CEX-withdrawal cohort of 71 voters does not normally all vote for the same project. Exchange withdrawals are individual decisions; the resulting on-chain activity disperses. A 71-voter cohort with 100% convergence on one project is one of two things — a coordinated voting bloc whose participants happened to fund from the same source, or an unusually concentrated genuine community pumping a project on behalf of the team behind it. We do not have on-chain evidence to discriminate between those two readings. We do have the concentration ratio (209/351 = 59.5% of the announced 1st-place winner's vote count coming from one upstream wallet's downstream voters), and the concentration ratio alone is incompatible with a random CEX-withdrawal-distribution interpretation.",
  "",
  "If `496d542527e1a29f57…` is a CEX hot wallet, the exchange (whichever it is) processed 71 customer withdrawals where every withdrawer subsequently voted for CasPay. If `496d542527e1a29f57…` is not a CEX, the contest's announced 1st-place winner had 59% of its vote count come from a single coordinating wallet. Both readings are findings; both readings can be checked further by anyone willing to query the wallet's outgoing-transfer patterns against the published voter pool.",
  "",
  "## What Casper paid",
  "",
  "We checked, for each of the top-7 project wallets that received FANR2 votes, every incoming CSPR transfer and every incoming CEP-18 fungible-token transfer (including USDC, USDT, and every other Casper stablecoin) recorded on mainnet after 5 February 2026 — the date of Casper's recap post that declared the winners.",
  "",
  "**Zero.** Zero CSPR transfers in. Zero CEP-18 transfers in. Zero outgoing activity. Across all seven top project wallets, every wallet sits dead.",
  "",
  "We cannot conclude from this that the winners were not paid at all. Casper Association may have paid the team operators directly to wallets other than the CSPR.fans-registered project shells, or off-chain in fiat, neither of which would be visible to us. We can only conclude that none of the announced winners' on-chain project shells received any visible payment from any source in any token after the contest's winner announcement.",
  "",
  "We also note that the top-7 project-shell wallets themselves have, between them, 1 or 2 lifetime deploys each. They are not the development wallets of working project teams. They are CSPR.fans-issued shell IDs assigned to project names by an off-chain database that Casper Association controls. The mapping from project name to wallet is a Casper-managed table; the chain records only what Casper chose to record.",
  "",
  "## What the community said, in real time",
  "",
  "We obtained the relevant fragments of a Casper-community Telegram conversation that took place during and immediately after the Final Round of voting (15–26 January 2026). Multiple participants raised the bot-vote alarm during the contest. One participant wrote:",
  "",
  "> day 1 of the final hackathon was a war of fake accounts. I thought it was too big to ignore, but I was wrong",
  "",
  "Day 1 of the Final Round was 15 January 2026 — the same day the FANR2 voting contract was deployed on mainnet (at 10:45 UTC) and the same day the wallet that funded 106 voters was first funded on-chain (at 22:07 UTC, eleven hours later). The chain confirms what the community member observed in real time.",
  "",
  "Another participant in the same conversation wrote:",
  "",
  "> less than a third of the accounts are fake and points have been suspended",
  "",
  "That is the Casper community's own description of Casper Association's response: an acknowledgment that at least a third of the accounts were fake, paired with a partial remediation (suspending some points), followed by declaring the winners on the contest's published schedule. Our independent on-chain measurement places the fake-account share at roughly two-thirds; the community description is a floor, not a ceiling.",
  "",
  "A third participant suggested an obvious fix that wasn't applied:",
  "",
  "> wouldn't the logical thing to do have been to close voting to accounts that were less than a month old?",
  "",
  "And a fourth referenced perpetrators publicly bragging in a Casper Twitter Space about exploiting the loopholes — discussed openly enough that other participants laughed about it. We have not located the Twitter Space recording.",
  "",
  "The same Telegram thread surfaces two Casper Association staffers by name: a person referenced as `@tamarawasserman` who received participant complaint emails, and a person referred to only as \"David\" who is described as the gatekeeper for access to the Casper Developer Telegram group. We surface these names because they appear in primary-source community communications acting in their professional capacity; their existence as named staff intersects with how the contest's complaints were routed (and not addressed in public).",
  "",
  "## Halborn was directly notified by a contestant",
  "",
  "Halborn Security appeared on the Casper Hackathon 2026 Final Round marketing banner as a co-sponsor. The logo of a Web3 security audit firm on a contest publicly framed as \"Sybil-resistant and fully transparent\" was a credibility-stamp. We have obtained primary-source evidence that a Casper Hackathon 2026 contestant — a builder who shipped a Final Round submission — had been in a continuous security-audit coordination relationship with a named Halborn representative since at least February 2025, and that this participant reported the unfolding bot-warfare situation directly to that Halborn contact while the contest was still ongoing and again afterward.",
  "",
  "The participant's verbatim message to their Halborn point of contact, with identifying details redacted (the participant's name, the Halborn representative's name, and the participant's project URL are all withheld to protect the source and to comply with their request not to be named):",
  "",
  "> the voting for the hackathon is based off the Casper Fans app and I've been auditing it for you and it's turning into a big botting war [...] it's mostly these teams from Turkey running 5-6 submissions and these guys from [region redacted by RexIntel — see note below] too [...] everyone in the hackathon is now botting so hard you guys would have to disqualify all the projects type thing if you really put a microscope on it, and there would be backlash if they take to X but none of them really have real X accounts.",
  "",
  "The same participant raised a separate hypothesis about why Casper Association appeared to be tolerating the situation:",
  "",
  "> I'm like not sure if this is like a marketing thing for you guys to show tons of transactions on the Casper Blockchain to inflate the traction for higher investment evaluations.",
  "",
  "This is the participant's hypothesis, not RexIntel's claim. We surface it because the alternative — that the Casper Association was unaware of the bot-driven on-chain traffic volume flowing through CSPR.fans during a contest they were running — is harder to credit given Casper's own community-side admission during the contest that \"less than a third of the accounts are fake and points have been suspended.\"",
  "",
  "What the participant's testimony adds to the case:",
  "",
  "1. **Halborn was informed by a contestant in real-time audit-coordination with them.** Whether Halborn's contracted scope of work on this hackathon included an audit of CSPR.fans, an audit of the FANR2 voting contract, or only of other Casper infrastructure, is something Halborn alone can clarify. What we can establish from the primary source is that a contestant who'd been doing audit-coordination work with Halborn since at least February 2025 escalated the bot-warfare findings to their Halborn contact directly.",
  "2. **The contestant's per-operator submission count is higher than our on-chain attribution.** The participant identified Turkish operator teams running \"5-6 submissions\" each. Our on-chain analysis documented a maximum of three submissions per operator (the abdul-kabugu cluster: BridgeX + anchor-protoco + Casper-FOMO). The 5-6 figure suggests some operators ran additional submissions — possibly including Round 1 (Qualification) entries — that we were not able to surface because the Round 1 voting contract was not findable on-chain.",
  "3. **\"None of them really have real X accounts\"** confirms what we'd already independently observed at the project level: the Anglo-sounding `@elontaylor1` X handle for CasPay being the most visible example. The operator-facing X handles are project-persona shells, separate from the real operator identities.",
  "4. **Geographic attribution note.** The participant identifies \"teams from Turkey\" (consistent with our on-chain attribution — Demirdöven, Furkan Ahmet Kara, mertksk) and operators from another region — the original message names a specific African country; our on-chain attribution placed `abdul-kabugu` in Bukoba, Tanzania, which is a different country from the one the participant named. Either the participant's geographic attribution is approximate (East/West African operators identified imprecisely), or there are additional African operators we did not surface on-chain. We redact the participant's specific geographic claim to avoid pinning unverified country-level attribution to operators we cannot confirm.",
  "",
  "What this does NOT establish: Halborn's response, whether Halborn acted on the information, whether Halborn relayed the findings to the Casper Association, or what Halborn's contracted scope of work actually covered. The participant's report to Halborn is a primary-source artifact. Halborn's response, at the time of this publication, had not yet arrived. We will update if Halborn responds publicly.",
  "",
  "## What happened in the private review calls",
  "",
  "Casper Association — operating through Make Software (the entity behind CSPR.fans and `cspr.live`) — held private recorded Zoom evaluations with select finalists in late January 2026. The communications came from `@make.services` email addresses. The agenda, provided verbatim, included project walkthrough, live demo of on-chain actions, mainnet roadmap, monetization plan, and Q&A. The technical requirements imposed on at least one reviewed entrant included: completing the GitHub Community Standards checklist, adding the `casper-blockchain` topic to repo metadata, enabling Dependabot, enabling CodeQL analysis, and fixing all high-severity-and-above CodeQL alerts. The session was declared recorded.",
  "",
  "We can independently observe two facts about how this private review applied:",
  "",
  "1. Several of the announced winners' project shells have one or two lifetime on-chain deploys each. The CodeQL audit standard and the \"live demo of on-chain actions\" standard could not have been applied to those teams in the same way as to a team that was demanded to produce production-grade security analysis.",
  "2. The recording was retained by Casper. It was not shared with the affected participants after the call. The asymmetry is the point: the entity making the subjective rejection decision is also the only entity holding the record of what was said during the decision-making process.",
  "",
  "## What we cannot say from this evidence",
  "",
  "We are deliberate about the line between what the on-chain record proves and what it does not.",
  "",
  "- We cannot prove that Casper Association coordinated with the bot operators. The Association's own wallet directly funded 34 voters and 4 of 7 winning shells; that is on-chain and verifiable. Whether that funding was knowing collusion or routine ecosystem expenditure that happened to flow to wallets the operators also used is not, by itself, demonstrable from this evidence.",
  "- We cannot prove that the winners were not paid. We can only prove they weren't paid on-chain to the wallets their CSPR.fans entries were registered against.",
  "- We cannot prove that all of the high-density Casper-address repositories we identified are AI-generated. We can prove that several of them were dumped to git as 30,000+ line first commits by single authors with no prior Casper history, which is the AI-generation fingerprint; the alternative — `git clone && git push` from a project developed elsewhere — would produce the same signature.",
  "- We cannot prove the 2nd-place winner's official Casper-Network repo contributions are remunerated. They are public, signed, and dated; whether they reflect a paid contributor relationship, an ambassador grant, or simply enthusiastic open-source contribution is not on the chain.",
  "",
  "We name these gaps because the case does not need to be stretched. The on-chain record alone — without speculation, without leaning on the chat logs, without the deleted repos — already proves: the voter pool was built specifically to vote and disappeared after; the top-tier projects' votes came overwhelmingly from a small number of operator-controlled funder clusters; one of the announced winners documented its own deployer wallet as the largest bot-funder in the contest; one operator submitted three different competing entries via shared wallets and won one prize.",
  "",
  "## How to verify this yourself",
  "",
  "Every claim in this piece is reproducible from public Casper mainnet data + public GitHub repositories. We're publishing the methodology so the community can run the same checks on the next contest. Two routes:",
  "",
  "### Route A — cspr.cloud API (free tier sign-up)",
  "",
  "Sign up at `cspr.cloud` for a free-tier API key (Make Software's public Casper indexer). Add the key as `Authorization: <key>` (no `Bearer` prefix) on every request. Then:",
  "",
  "- **Contract metadata** — `GET https://api.cspr.cloud/contract-packages/{package_hash}` returns the contract name, symbol, owner public key, and deploy timestamp. For the FANR2 voting contract: `package_hash = cbf2518437fbf7f8bdc895dad8eb1bcc5ea4fa0b7978b33721ea73366ad42428`.",
  "- **Every deploy that called a contract** — `GET /deploys?contract_package_hash={hash}&page_size=250&page=N` paginates the complete call history. For the FANR2 vote contract you get 1,869 deploys; each carries `caller_hash`, `caller_public_key`, `args.voter`, `args.project`, `args.token_amount`, `args.vote_id`, `args.signature`, `timestamp`, `block_hash`, `block_height`.",
  "- **Account info by pubkey or hash** — `GET /accounts/{pubkey_or_hash}` returns balance, account_hash, public_key, named_keys, associated_keys. This is how you check whether a wallet you found in code is real on mainnet.",
  "- **Account transfer history** — `GET /accounts/{pubkey}/transfers?page_size=250&page=N`. The OLDEST page (`page=page_count`) gives you the first incoming transfer — i.e. who funded the wallet. This is the building block of the funding-pyramid analysis.",
  "- **CEP-18 token-action log** — `GET /contract-packages/{hash}/ft-token-actions?page_size=250&page=N`. Returns every mint (`from_hash: null`) and transfer of the fungible token. For FANR2: 1,838 mints, 10 transfers, 45 unique mint recipients (all projects).",
  "",
  "### Route B — Tatum free RPC (no signup)",
  "",
  "If you don't want to sign up for cspr.cloud, Tatum's gateway at `https://casper-mainnet.gateway.tatum.io` accepts standard Casper JSON-RPC unauthenticated at 5 requests/minute — slow but free. Useful for spot-checks of `state_get_account_info`, `info_get_deploy`, and `chain_get_block`. cspr.live's frontend is the human-readable presentation of the same data.",
  "",
  "### Analyses anyone can run",
  "",
  "Once you have the deploy list for a voting contract, every analysis in this piece is reachable from there:",
  "",
  "- **Voter freshness percentage:** for each unique `args.voter` account-hash, query `/accounts/{voter_pk}/deploys?page=1&page_size=1` (then `page={page_count}` to get the oldest). Compare the oldest-deploy timestamp to the voter's first vote timestamp. If the difference is under 24h, the voter was \"fresh-baked.\"",
  "- **Post-event dormancy:** for each voter, compare the newest-deploy timestamp to the contest's end date. If the latest activity is before the announcement, the voter is dormant.",
  "- **Templated-vote percentage:** count the distribution of `args.token_amount` values across all deploys. A skewed distribution toward a single value (here 1,000) signals max-allocation rather than community splitting.",
  "- **Funding pyramid:** for each voter, find their first funder via the transfers endpoint. Group voters by first-funder. The top-N funders by voter count reveal the structure.",
  "- **Per-project funder concentration:** for each project (recipient in `args.project`), bucket its voters by their respective first-funders. A project where one funder accounts for >50% of voters has a single-cluster origin.",
  "- **Funding-to-voting latency:** subtract the voter's first-funding timestamp from their first-vote timestamp. Values under 60 seconds are script-fired.",
  "- **Cross-project deployer search:** clone each project repository, grep for `(02|01)[0-9a-fA-F]{64,66}` (Casper public keys) and `account-hash-[0-9a-fA-F]{64}` (account hashes). Enrich every hit against `/accounts/{address}` to filter false positives. Any address that appears in 2+ repositories is a cross-project deployer link worth investigating.",
  "- **Cross-project commit-email overlap:** for every alive repo, hit `GET https://api.github.com/repos/{owner}/{repo}/commits?per_page=100` and harvest `commit.author.email`. The same email in two different teams' repos is a cross-team identity match.",
  "",
  "We are publishing the on-chain dataset, the cleaned voter list, the funding-graph CSVs, and the cross-project address-collision results behind RexIntel's contributor-tier wallet gate. Connect a Casper or Circle wallet, contribute one accepted intel item, and the toolkit becomes available. The point isn't to keep this in our hands — it's to make running the same checks on the next contest a one-day project for anyone willing to clone a repo and read a JSON response.",
  "",
  "## What this adds up to",
  "",
  "Casper Hackathon 2026 was marketed as a community-decided contest with Sybil resistance and on-chain transparency. The contract Casper deployed has no on-chain Sybil resistance because the voting authority is the off-chain CSPR.fans server that the Casper Association operates. The official rules permitted projects with no code, no testnet, and no GitHub to advance to the finals. The Casper Association reserved an explicit override of the community-vote selection in its own announcement.",
  "",
  "The chain shows that the option was exercised. The voter pool was built for the occasion and dispersed afterward. The top projects' votes came from operator-controlled clusters that included, in the documented case of CasperLink, the same wallet the announced 3rd-place team used as its project owner. Three of the four announced winners trace to socially or financially connected operator clusters across Turkey and Bukoba, Tanzania. The community knew during the contest; Casper acknowledged the fake-account presence to its community, declared winners anyway, and held private reviews of selected finalists with recordings it kept to itself.",
  "",
  "What the on-chain record disproves, beyond a reasonable framing of the available evidence, is the central marketing claim: that the winners of Casper Hackathon 2026 were selected by a Sybil-resistant community vote.",
  "",
  "## Evidence index",
  "",
  "Every claim in this piece is independently verifiable from public Casper mainnet data and public GitHub repositories. The receipts:",
  "",
  "**The voting contract**",
  "- FANR2 voting contract package: `cbf2518437fbf7f8bdc895dad8eb1bcc5ea4fa0b7978b33721ea73366ad42428`",
  "- Explorer: https://cspr.live/contract-package/cbf2518437fbf7f8bdc895dad8eb1bcc5ea4fa0b7978b33721ea73366ad42428",
  "- Contract owner (Casper Association operational wallet): account-hash `0bc9335b32b92985dd765680d3e058cf060efc1fba295f1b6342f58ea04f5d65` / pubkey `020322ea4248fb7a557dff9e18f3cfd3ccafb2e77cf89a50f01070f33d5618cb4586`",
  "- Contract version 1 deployed 2026-01-15T10:45:55Z; replaced by version 2 on 2026-01-20T11:15:59Z mid-vote",
  "",
  "**CasperLink's documented owner wallet (= apex bot-funder)**",
  "- account-hash `74ab92cebdb16189b8a1d3ed5a87d6fff8df694e9ede46393b5e11bb441be597`",
  "- pubkey `02031ed02f6abebdec47e03f18bc1ee37fcae4d999e82a4f49512c8d25489dfd5302`",
  "- Identified in `SohamJuneja/CasperLink/phase1.md` as \"Account Hash (Owner)\"",
  "- First funded on mainnet 2026-01-15T22:07:15Z; 212 lifetime deploys; 209 transfers; ~345 CSPR balance",
  "",
  "**Other operator-cluster funder wallets**",
  "- `41e4339ebc8a4f2941be99cc64fabb028be6fca8dd071ba7fbebfec13533fb37` — funded 88 voters; 10 of the 15 fastest fund→vote voters were downstream of this wallet",
  "- `34a4df50b943e5dfc95598e797e2f4184cfadfad06eddf8a99a6809883b00adf` — funded 34 voters",
  "- `eb747cd191aa5d8403606d05094153f2ad282c949987e3c4740143658bdc7af4` — funded 27 voters",
  "",
  "**Edge-of-case funder wallets (Guns 9 + 10)**",
  "- `65a1bb912303cdaa01a7b07c9ad5bef91dbf45d6cd9d9f3dc69eecd3a8aebcca` — 67 seconds apart, seeded two top-7 project shells (`24df63ca…` and `6b3559aa…`) with 2.5 CSPR each. 2023-era community wallet, only funded 1 voter directly. One operator, two competing project entries.",
  "- `496d542527e1a29f576ab7c3f4c947bfcdc9b4145f75f6ec40e36089432d7351` — 71 voters funded by this wallet collectively cast 209 votes for project `9842d06f…` (announced 1st-place winner CasPay), accounting for 59.5% of CasPay's total vote count. 5-year-old account, 91M CSPR balance, profile consistent with either a CEX hot wallet or a sophisticated coordinated funder.",
  "",
  "**Casper Association direct voter fundings**",
  "- The Association wallet (`0bc9335b…`) directly funded 34 voter wallets with 535 CSPR (mean ~16 CSPR each)",
  "- Funded 4 of 7 top-vote project shells with first transfers of exactly 2.5 CSPR each: `9842d06f…`, `4d47ac81…`, `066662e9…`, `ce509235…`",
  "- Three of those four shells were created in a six-second window on 2026-01-07 between 14:05:31 and 14:05:37 UTC",
  "",
  "**Cross-project commit-author emails**",
  "- `mert_ksk_1998@hotmail.com` — appears in commit logs of both `mertksk/accelerate` and `furkanahmetk/shroud-protocol` (the announced 2nd-place winner)",
  "- `kabuguabdul2@gmail.com` — appears in commit logs of both `BridgeX-dapp/bridgeX` (announced Interop winner) and `anchor-protoco/protocol`",
  "",
  "**Deleted repositories of note**",
  "- `dmrdvn/caspay` — the announced 1st-place winner's repository",
  "- `osas2211/sampled-casper`",
  "- `StudioLIQ/gaspar-finance`",
  "- `x5engine/CasperGhost-The-Autonomous-DeFi-Agent`",
  "- `fullendmaestro/anchore`",
  "- `HoomanBuilds/agentis`",
  "- `luxipha/CasperID`",
  "- `mja2001/SolCipher-Casper`",
  "",
  "**Official Casper sources cited**",
  "- Casper Hackathon 2026 announcement: https://www.casper.network/news/casper-hackathon-2026-build-vote-shape-the-future-of-the-network",
  "- CSPR.fans launch post (points mechanism): https://www.casper.network/news/cspr-fans",
  "- 5 February 2026 recap with winners and \"Sybil resistance\" claim: https://www.casper.network/news/casper-x-space-recap-feb-5-2026-parking-mvp-goes-live-defi-expands-hackathon-winners-and-live-q-a",
  "- DoraHacks Final Round + Community Choice Fast-Track rules: https://dorahacks.io/hackathon/casper-hackathon-2026-finals",
  "",
  "All on-chain claims in this piece were independently verified against the cspr.cloud REST API and cross-referenced with cspr.live. All GitHub claims were verified via the GitHub REST API. The investigation was conducted by RexIntel.",
].join("\n");

const payload: IntelPayload = {
  headline: HEADLINE,
  body,
  bodyFormat: "markdown",
  // One-line standfirst — sits between headline and hero on the article
  // page, drives the meta description, and is the search-result snippet.
  dek:
    "On-chain forensics from the FANR2 voting contract: 96% of the voter pool was fed by 15 apex wallets, the 3rd-place winner's deployer was the largest single bot-funder, and the Casper Association itself seeded both the voter pool and the project shells.",
  // Hero image — a typographic stat card published from /public. Renders as
  // the og:image, the listing thumbnail, the RSS media:content enclosure,
  // and the article hero. Anonymous-source convention: credit is RexIntel,
  // not the contributor.
  heroImageUrl: "/intel-heroes/casper-hackathon-expose.svg",
  heroAlt:
    "Casper Hackathon 2026 — 96 percent of the voter pool was fed by 15 apex wallets. The announced 3rd-place winner's documented deployer wallet was the apex bot-funder behind 106 of the votes.",
  heroCaption:
    "96% of the voter pool traces back to 15 apex wallets. The announced 3rd-place winner's documented deployer wallet was the apex bot-funder behind 106 of the votes.",
  heroCredit: "Rex Intel Services · Investigations Desk",
  // Evidence gallery — direct links to the primary on-chain receipts so any
  // reader can re-run the verification without leaving the article. The
  // gallery renders below the body as a stacked "Evidence" block.
  media: [
    {
      kind: "embed",
      url: "https://cspr.live/contract-package/cbf2518437fbf7f8bdc895dad8eb1bcc5ea4fa0b7978b33721ea73366ad42428",
      caption:
        "FANR2 voting contract on cspr.live — 1,869 deploys, 751 unique voters, 45 mint recipients.",
      credit: "cspr.live (Make Software)",
    },
    {
      kind: "embed",
      url: "https://cspr.live/account/02031ed02f6abebdec47e03f18bc1ee37fcae4d999e82a4f49512c8d25489dfd5302",
      caption:
        "CasperLink's documented owner wallet — same wallet that funded 106 voters in the contest.",
      credit: "cspr.live",
    },
    {
      kind: "embed",
      url: "https://github.com/SohamJuneja/CasperLink",
      caption:
        "The CasperLink repository where the 3rd-place team identifies the apex bot-funder wallet as the project's owner.",
      credit: "GitHub",
    },
    {
      kind: "image",
      url: "/casper.png",
      alt: "Casper Hackathon 2026 — Final Round. Prize: $40,000 ($25K cash, $5K NodeOps credit, $10K ChainGPT API grant). Co-sponsored by Halborn, NowNodes, NodeOps, ChainGPT.",
      caption:
        "Casper Hackathon 2026 — Final Round. The official promotional artwork for the contest examined above.",
      credit: "Casper Association",
    },
  ],
  kind: "incident",
  category: "Hackathon fraud",
  severity: "critical",
  sourceGrade: "primary",
  anonymous: true,
  spicy: true,
  // Audience: builders considering Casper hackathons (founder/developer),
  // ecosystem-watchers (investigator/journalist), and anyone allocating
  // grants to Casper (fund-risk).
  personas: ["founder", "developer", "investor", "investigator", "journalist", "fund-risk"],
  sources: [
    "https://www.casper.network/news/casper-hackathon-2026-build-vote-shape-the-future-of-the-network",
    "https://www.casper.network/news/cspr-fans",
    "https://www.casper.network/news/casper-x-space-recap-feb-5-2026-parking-mvp-goes-live-defi-expands-hackathon-winners-and-live-q-a",
    "https://dorahacks.io/hackathon/casper-hackathon-2026-finals",
    "https://cspr.live/contract-package/cbf2518437fbf7f8bdc895dad8eb1bcc5ea4fa0b7978b33721ea73366ad42428",
    "https://github.com/SohamJuneja/CasperLink",
    "https://github.com/casper-network/casper-nctl",
    "https://github.com/furkanahmetk/shroud-protocol",
    "https://github.com/BridgeX-dapp/bridgeX",
    "https://github.com/anchor-protoco/protocol",
  ],
  links: [
    "https://cspr.live/account/02031ed02f6abebdec47e03f18bc1ee37fcae4d999e82a4f49512c8d25489dfd5302",
    "https://cspr.live/account/020322ea4248fb7a557dff9e18f3cfd3ccafb2e77cf89a50f01070f33d5618cb4586",
  ],
};

async function main() {
  const now = new Date();

  const existing = await db
    .select({ id: submissions.id, publicId: submissions.publicId })
    .from(submissions)
    .where(eq(sql`${submissions.payload}->>'headline'`, HEADLINE))
    .limit(1);

  if (existing.length) {
    const row = existing[0];
    await db
      .update(submissions)
      .set({
        payload,
        status: "approved",
        featured: true,
        publishedAt: now,
        updatedAt: now,
        submitterHandle: "RexIntel",
      })
      .where(eq(submissions.id, row.id));
    console.log(`Updated existing exposé row (id=${row.id}, publicId=${row.publicId})`);
    console.log(`  /intel/${row.publicId}`);
  } else {
    const [inserted] = await db
      .insert(submissions)
      .values({
        type: "intel",
        status: "approved",
        payload,
        submitterHandle: "RexIntel",
        publishedAt: now,
        featured: true,
      })
      .returning({ id: submissions.id, publicId: submissions.publicId });
    console.log(`Inserted exposé (id=${inserted.id}, publicId=${inserted.publicId})`);
    console.log(`  /intel/${inserted.publicId}`);
  }

  console.log(`\nFeatured at the top of /intel signals lane.`);
  console.log(`Body length: ${body.length} chars`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
